/**
 * @file    Com_Cfg_Fzc.c
 * @brief   Com module configuration for FZC — TX/RX PDUs and signal mappings
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Com.h"
#include "Fzc_Cfg.h"

/* ==================================================================
 * Shadow Buffers (static RAM for signal read/write)
 * ================================================================== */

/* TX signal buffers */
static uint8_t  sig_tx_fzc_heartbeat_e2e_dataid;
static uint8_t  sig_tx_fzc_heartbeat_e2e_alivecounter;
static uint8_t  sig_tx_fzc_heartbeat_e2e_crc8;
static uint8_t  sig_tx_fzc_heartbeat_ecu_id;
static uint8_t  sig_tx_fzc_heartbeat_operatingmode;
static uint8_t  sig_tx_fzc_heartbeat_faultstatus;
static uint8_t  sig_tx_steering_status_e2e_dataid;
static uint8_t  sig_tx_steering_status_e2e_alivecounter;
static uint8_t  sig_tx_steering_status_e2e_crc8;
static uint16_t  sig_tx_steering_status_actualangle;
static uint16_t  sig_tx_steering_status_commandedangle;
static uint8_t  sig_tx_steering_status_steerfaultstatus;
static uint8_t  sig_tx_steering_status_steermode;
static uint8_t  sig_tx_steering_status_servocurrent_ma;
static uint8_t  sig_tx_brake_status_e2e_dataid;
static uint8_t  sig_tx_brake_status_e2e_alivecounter;
static uint8_t  sig_tx_brake_status_e2e_crc8;
static uint8_t  sig_tx_brake_status_brakeposition;
static uint8_t  sig_tx_brake_status_brakecommandecho;
static uint16_t  sig_tx_brake_status_servocurrent_ma;
static uint8_t  sig_tx_brake_status_brakefaultstatus;
static uint8_t  sig_tx_brake_status_brakemode;
static uint8_t  sig_tx_brake_fault_e2e_dataid;
static uint8_t  sig_tx_brake_fault_e2e_alivecounter;
static uint8_t  sig_tx_brake_fault_e2e_crc8;
static uint8_t  sig_tx_brake_fault_faulttype;
static uint8_t  sig_tx_brake_fault_commandedbrake;
static uint8_t  sig_tx_brake_fault_measuredbrake;
static uint8_t  sig_tx_motor_cutoff_req_e2e_dataid;
static uint8_t  sig_tx_motor_cutoff_req_e2e_alivecounter;
static uint8_t  sig_tx_motor_cutoff_req_e2e_crc8;
static uint8_t  sig_tx_motor_cutoff_req_requesttype;
static uint8_t  sig_tx_motor_cutoff_req_reason;
static uint8_t  sig_tx_lidar_distance_e2e_dataid;
static uint8_t  sig_tx_lidar_distance_e2e_alivecounter;
static uint8_t  sig_tx_lidar_distance_e2e_crc8;
static uint16_t  sig_tx_lidar_distance_range_cm;
static uint16_t  sig_tx_lidar_distance_signalstrength;
static uint8_t  sig_tx_lidar_distance_obstaclezone;
static uint8_t  sig_tx_lidar_distance_sensorstatus;
static uint16_t  sig_tx_dtc_broadcast_number;
static uint8_t  sig_tx_dtc_broadcast_status;
static uint8_t  sig_tx_dtc_broadcast_ecu_source;
static uint8_t  sig_tx_dtc_broadcast_occurrencecount;
static uint8_t  sig_tx_dtc_broadcast_freezeframe0;
static uint8_t  sig_tx_dtc_broadcast_freezeframe1;
static uint32_t  sig_tx_xcp_resp_fzc_data;
static uint32_t  sig_tx_uds_resp_fzc_uds_data;

/* RX signal buffers */
static uint8_t  sig_rx_estop_broadcast_e2e_dataid;
static uint8_t  sig_rx_estop_broadcast_e2e_alivecounter;
static uint8_t  sig_rx_estop_broadcast_e2e_crc8;
static uint8_t  sig_rx_estop_broadcast_active;
static uint8_t  sig_rx_estop_broadcast_source;
static uint8_t  sig_rx_cvc_heartbeat_e2e_dataid;
static uint8_t  sig_rx_cvc_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_cvc_heartbeat_e2e_crc8;
static uint8_t  sig_rx_cvc_heartbeat_ecu_id;
static uint8_t  sig_rx_cvc_heartbeat_operatingmode;
static uint8_t  sig_rx_cvc_heartbeat_faultstatus;
static uint8_t  sig_rx_rzc_heartbeat_e2e_dataid;
static uint8_t  sig_rx_rzc_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_rzc_heartbeat_e2e_crc8;
static uint8_t  sig_rx_rzc_heartbeat_ecu_id;
static uint8_t  sig_rx_rzc_heartbeat_operatingmode;
static uint8_t  sig_rx_rzc_heartbeat_faultstatus;
static uint8_t  sig_rx_sc_status_alivecounter;
static uint8_t  sig_rx_sc_status_crc8;
static uint8_t  sig_rx_sc_status_mode;
static uint8_t  sig_rx_sc_status_faultflags;
static uint8_t  sig_rx_sc_status_ecu_health;
static uint8_t  sig_rx_sc_status_faultreason;
static boolean  sig_rx_sc_status_relayenergized;
static uint8_t  sig_rx_icu_heartbeat_e2e_dataid;
static uint8_t  sig_rx_icu_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_icu_heartbeat_e2e_crc8;
static uint8_t  sig_rx_icu_heartbeat_alivecounter;
static uint8_t  sig_rx_icu_heartbeat_ecu_id;
static uint8_t  sig_rx_tcu_heartbeat_e2e_dataid;
static uint8_t  sig_rx_tcu_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_tcu_heartbeat_e2e_crc8;
static uint8_t  sig_rx_tcu_heartbeat_alivecounter;
static uint8_t  sig_rx_tcu_heartbeat_ecu_id;
static uint8_t  sig_rx_bcm_heartbeat_e2e_dataid;
static uint8_t  sig_rx_bcm_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_bcm_heartbeat_e2e_crc8;
static uint8_t  sig_rx_bcm_heartbeat_alivecounter;
static uint8_t  sig_rx_bcm_heartbeat_ecu_id;
static uint8_t  sig_rx_vehicle_state_e2e_dataid;
static uint8_t  sig_rx_vehicle_state_e2e_alivecounter;
static uint8_t  sig_rx_vehicle_state_e2e_crc8;
static uint8_t  sig_rx_vehicle_state_mode;
static uint16_t  sig_rx_vehicle_state_faultmask;
static uint8_t  sig_rx_vehicle_state_torquelimit;
static uint8_t  sig_rx_vehicle_state_speedlimit;
static uint8_t  sig_rx_torque_request_e2e_dataid;
static uint8_t  sig_rx_torque_request_e2e_alivecounter;
static uint8_t  sig_rx_torque_request_e2e_crc8;
static uint8_t  sig_rx_torque_request_command_pct;
static uint8_t  sig_rx_torque_request_direction;
static uint16_t  sig_rx_torque_request_pedalposition1;
static uint16_t  sig_rx_torque_request_pedalposition2;
static boolean  sig_rx_torque_request_pedalfault;
static uint8_t  sig_rx_steer_command_e2e_dataid;
static uint8_t  sig_rx_steer_command_e2e_alivecounter;
static uint8_t  sig_rx_steer_command_e2e_crc8;
static uint16_t  sig_rx_steer_command_steeranglecmd;
static uint8_t  sig_rx_steer_command_steerratelimit;
static uint8_t  sig_rx_steer_command_vehiclestate;
static uint8_t  sig_rx_brake_command_e2e_dataid;
static uint8_t  sig_rx_brake_command_e2e_alivecounter;
static uint8_t  sig_rx_brake_command_e2e_crc8;
static uint8_t  sig_rx_brake_command_brakeforcecmd;
static uint8_t  sig_rx_brake_command_brakemode;
static uint8_t  sig_rx_brake_command_vehiclestate;
static uint8_t  sig_rx_motor_status_e2e_dataid;
static uint8_t  sig_rx_motor_status_e2e_alivecounter;
static uint8_t  sig_rx_motor_status_e2e_crc8;
static uint8_t  sig_rx_motor_status_torqueecho;
static uint16_t  sig_rx_motor_status_motorspeed_rpm;
static uint8_t  sig_rx_motor_status_motordirection;
static uint8_t  sig_rx_motor_status_motorenable;
static uint8_t  sig_rx_motor_status_motorfaultstatus;
static uint8_t  sig_rx_motor_current_e2e_dataid;
static uint8_t  sig_rx_motor_current_e2e_alivecounter;
static uint8_t  sig_rx_motor_current_e2e_crc8;
static uint16_t  sig_rx_motor_current_phase_ma;
static boolean  sig_rx_motor_current_dirisreverse;
static boolean  sig_rx_motor_current_motorenable;
static boolean  sig_rx_motor_current_overcurrentflag;
static uint8_t  sig_rx_motor_current_torqueecho;
static uint8_t  sig_rx_motor_temperature_e2e_dataid;
static uint8_t  sig_rx_motor_temperature_e2e_alivecounter;
static uint8_t  sig_rx_motor_temperature_e2e_crc8;
static uint16_t  sig_rx_motor_temperature_windingtemp1_c;
static uint16_t  sig_rx_motor_temperature_windingtemp2_c;
static uint8_t  sig_rx_motor_temperature_deratingpercent;
static uint8_t  sig_rx_battery_status_e2e_dataid;
static uint8_t  sig_rx_battery_status_e2e_alivecounter;
static uint8_t  sig_rx_battery_status_e2e_crc8;
static uint16_t  sig_rx_battery_status_batteryvoltage_mv;
static uint8_t  sig_rx_battery_status_level;
static uint8_t  sig_rx_body_control_cmd_headlightcmd;
static boolean  sig_rx_body_control_cmd_taillighton;
static boolean  sig_rx_body_control_cmd_hazardactive;
static uint8_t  sig_rx_body_control_cmd_turnsignalcmd;
static boolean  sig_rx_body_control_cmd_doorlockcmd;
static boolean  sig_rx_light_status_headlighton;
static boolean  sig_rx_light_status_taillighton;
static boolean  sig_rx_light_status_foglighton;
static boolean  sig_rx_light_status_brakelighton;
static uint8_t  sig_rx_light_status_headlightlevel;
static boolean  sig_rx_indicator_state_lefton;
static boolean  sig_rx_indicator_state_righton;
static boolean  sig_rx_indicator_state_hazardactive;
static boolean  sig_rx_indicator_state_blinkphasehigh;
static boolean  sig_rx_door_lock_status_frontleftlock;
static boolean  sig_rx_door_lock_status_frontrightlock;
static boolean  sig_rx_door_lock_status_rearleftlock;
static boolean  sig_rx_door_lock_status_rearrightlock;
static boolean  sig_rx_door_lock_status_centrallock;
static uint16_t  sig_rx_dtc_broadcast_number;
static uint8_t  sig_rx_dtc_broadcast_status;
static uint8_t  sig_rx_dtc_broadcast_ecu_source;
static uint8_t  sig_rx_dtc_broadcast_occurrencecount;
static uint8_t  sig_rx_dtc_broadcast_freezeframe0;
static uint8_t  sig_rx_dtc_broadcast_freezeframe1;
static uint32_t  sig_rx_xcp_req_cvc_data;
static uint32_t  sig_rx_xcp_resp_cvc_data;
static uint32_t  sig_rx_xcp_req_fzc_data;
static uint32_t  sig_rx_xcp_req_rzc_data;
static uint32_t  sig_rx_xcp_resp_rzc_data;
static uint32_t  sig_rx_xcp_req_sc_data;
static uint32_t  sig_rx_xcp_resp_sc_data;
static uint16_t  sig_rx_fzc_virtual_sensors_steerangle_raw;
static uint16_t  sig_rx_fzc_virtual_sensors_brakepos_adc;
static uint16_t  sig_rx_fzc_virtual_sensors_brakecurrent_ma;
static uint16_t  sig_rx_rzc_virtual_sensors_motorcurrent_ma;
static uint16_t  sig_rx_rzc_virtual_sensors_motortemp_dc;
static uint16_t  sig_rx_rzc_virtual_sensors_battvoltage_mv;
static uint16_t  sig_rx_rzc_virtual_sensors_motorspeed_rpm;
static uint32_t  sig_rx_uds_resp_tcu_uds_data;
static uint32_t  sig_rx_uds_func_request_uds_data;
static uint32_t  sig_rx_uds_phys_req_cvc_uds_data;
static uint32_t  sig_rx_uds_phys_req_fzc_uds_data;
static uint32_t  sig_rx_uds_phys_req_rzc_uds_data;
static uint32_t  sig_rx_uds_phys_req_tcu_uds_data;
static uint32_t  sig_rx_uds_resp_cvc_uds_data;
static uint32_t  sig_rx_uds_resp_rzc_uds_data;

/* ==================================================================
 * Signal Configuration Table
 * Maps signal ID -> bit position, size, type, parent PDU, shadow buffer
 * ================================================================== */

/* TX signal table — iterated by Com_MainFunction_Tx auto-pull */
static const Com_SignalConfigType fzc_tx_signal_config[] = {
    /* id, bitPos, bitSize, type,       pduId,                      shadowBuf,       rteSignalId,  updateBit */
    {  0u,    0u,     4u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  1u,    4u,     4u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  2u,    8u,     8u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  3u,   16u,     8u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_ecu_id, FZC_SIG_FZC_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    {  4u,   24u,     4u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_operatingmode, FZC_SIG_FZC_HEARTBEAT_OPERATING_MODE, COM_NO_UPDATE_BIT },
    {  5u,   28u,     4u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_faultstatus, FZC_SIG_FZC_HEARTBEAT_FAULT_STATUS, COM_NO_UPDATE_BIT },
    {  6u,    0u,     4u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  7u,    4u,     4u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  8u,    8u,     8u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  9u,   16u,    16u, COM_UINT16, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_actualangle, FZC_SIG_STEERING_STATUS_ACTUAL_ANGLE, COM_NO_UPDATE_BIT },
    { 10u,   32u,    16u, COM_UINT16, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_commandedangle, FZC_SIG_STEERING_STATUS_COMMANDED_ANGLE, COM_NO_UPDATE_BIT },
    { 11u,   48u,     4u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_steerfaultstatus, FZC_SIG_STEERING_STATUS_STEER_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 12u,   52u,     4u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_steermode, FZC_SIG_STEERING_STATUS_STEER_MODE, COM_NO_UPDATE_BIT },
    { 13u,   56u,     8u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_servocurrent_ma, FZC_SIG_STEERING_STATUS_SERVO_CURRENT_M_A, COM_NO_UPDATE_BIT },
    { 14u,    0u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 15u,    4u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 16u,    8u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 17u,   16u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_brakeposition, FZC_SIG_BRAKE_STATUS_BRAKE_POSITION, COM_NO_UPDATE_BIT },
    { 18u,   24u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_brakecommandecho, FZC_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO, COM_NO_UPDATE_BIT },
    { 19u,   32u,    16u, COM_UINT16, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_servocurrent_ma, FZC_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A, COM_NO_UPDATE_BIT },
    { 20u,   48u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_brakefaultstatus, FZC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 21u,   52u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_brakemode, FZC_SIG_BRAKE_STATUS_BRAKE_MODE, COM_NO_UPDATE_BIT },
    { 22u,    0u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 23u,    4u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 24u,    8u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 25u,   16u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_faulttype, FZC_SIG_BRAKE_FAULT_FAULT_TYPE, COM_NO_UPDATE_BIT },
    { 26u,   20u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_commandedbrake, FZC_SIG_BRAKE_FAULT_COMMANDED_BRAKE, COM_NO_UPDATE_BIT },
    { 27u,   28u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_measuredbrake, FZC_SIG_BRAKE_FAULT_MEASURED_BRAKE, COM_NO_UPDATE_BIT },
    { 28u,    0u,     4u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 29u,    4u,     4u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 30u,    8u,     8u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 31u,   16u,     4u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_requesttype, FZC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE, COM_NO_UPDATE_BIT },
    { 32u,   20u,     4u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_reason, FZC_SIG_MOTOR_CUTOFF_REQ_REASON, COM_NO_UPDATE_BIT },
    { 33u,    0u,     4u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 34u,    4u,     4u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 35u,    8u,     8u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 36u,   16u,    16u, COM_UINT16, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_range_cm, FZC_SIG_LIDAR_DISTANCE_RANGE_CM, COM_NO_UPDATE_BIT },
    { 37u,   32u,    16u, COM_UINT16, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_signalstrength, FZC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH, COM_NO_UPDATE_BIT },
    { 38u,   48u,     4u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_obstaclezone, FZC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE, COM_NO_UPDATE_BIT },
    { 39u,   52u,     4u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_sensorstatus, FZC_SIG_LIDAR_DISTANCE_SENSOR_STATUS, COM_NO_UPDATE_BIT },
    { 40u,    7u,    16u, COM_UINT16, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_number, FZC_SIG_DTC_BROADCAST_NUMBER, COM_NO_UPDATE_BIT },
    { 41u,   24u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_status, FZC_SIG_DTC_BROADCAST_STATUS, COM_NO_UPDATE_BIT },
    { 42u,   32u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_ecu_source, FZC_SIG_DTC_BROADCAST_ECU_SOURCE, COM_NO_UPDATE_BIT },
    { 43u,   40u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_occurrencecount, FZC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT, COM_NO_UPDATE_BIT },
    { 44u,   48u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_freezeframe0, FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_0, COM_NO_UPDATE_BIT },
    { 45u,   56u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_freezeframe1, FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_1, COM_NO_UPDATE_BIT },
    { 46u,    0u,    64u, COM_UINT32, FZC_COM_TX_XCP_RESP_FZC, &sig_tx_xcp_resp_fzc_data, FZC_SIG_XCP_RESP_FZC_DATA, COM_NO_UPDATE_BIT },
    { 47u,    0u,    64u, COM_UINT32, FZC_COM_TX_UDS_RESP_FZC, &sig_tx_uds_resp_fzc_uds_data, FZC_SIG_UDS_RESP_FZC_UDS_DATA, COM_NO_UPDATE_BIT },
};

#define FZC_COM_TX_SIGNAL_COUNT  (sizeof(fzc_tx_signal_config) / sizeof(fzc_tx_signal_config[0]))

/* RX signal table — iterated by Com_RxIndication auto-push */
static const Com_SignalConfigType fzc_rx_signal_config[] = {
    /* id, bitPos, bitSize, type,       pduId,                      shadowBuf,       rteSignalId,  updateBit */
    {  0u,    0u,     4u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_dataid, FZC_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    {  1u,    4u,     4u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_alivecounter, FZC_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    {  2u,    8u,     8u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_crc8, FZC_SIG_ESTOP_BROADCAST_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    {  3u,   16u,     8u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_active, FZC_SIG_ESTOP_BROADCAST_ACTIVE, COM_NO_UPDATE_BIT },
    {  4u,   24u,     8u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_source, FZC_SIG_ESTOP_BROADCAST_SOURCE, COM_NO_UPDATE_BIT },
    {  5u,    0u,     4u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_dataid, FZC_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    {  6u,    4u,     4u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_alivecounter, FZC_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    {  7u,    8u,     8u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_crc8, FZC_SIG_CVC_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    {  8u,   16u,     8u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_ecu_id, FZC_SIG_CVC_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    {  9u,   24u,     4u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_operatingmode, FZC_SIG_CVC_HEARTBEAT_OPERATING_MODE, COM_NO_UPDATE_BIT },
    { 10u,   28u,     4u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_faultstatus, FZC_SIG_CVC_HEARTBEAT_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 11u,    0u,     4u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_e2e_dataid, FZC_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 12u,    4u,     4u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_e2e_alivecounter, FZC_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 13u,    8u,     8u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_e2e_crc8, FZC_SIG_RZC_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 14u,   16u,     8u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_ecu_id, FZC_SIG_RZC_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 15u,   24u,     4u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_operatingmode, FZC_SIG_RZC_HEARTBEAT_OPERATING_MODE, COM_NO_UPDATE_BIT },
    { 16u,   28u,     4u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_faultstatus, FZC_SIG_RZC_HEARTBEAT_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 17u,    0u,     8u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_alivecounter, FZC_SIG_SC_STATUS_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 18u,    8u,     8u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_crc8, FZC_SIG_SC_STATUS_CRC_8, COM_NO_UPDATE_BIT },
    { 19u,   16u,     4u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_mode, FZC_SIG_SC_STATUS_MODE, COM_NO_UPDATE_BIT },
    { 20u,   20u,     4u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_faultflags, FZC_SIG_SC_STATUS_FAULT_FLAGS, COM_NO_UPDATE_BIT },
    { 21u,   24u,     3u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_ecu_health, FZC_SIG_SC_STATUS_ECU_HEALTH, COM_NO_UPDATE_BIT },
    { 22u,   27u,     4u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_faultreason, FZC_SIG_SC_STATUS_FAULT_REASON, COM_NO_UPDATE_BIT },
    { 23u,   31u,     1u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_relayenergized, FZC_SIG_SC_STATUS_RELAY_ENERGIZED, COM_NO_UPDATE_BIT },
    { 24u,    0u,     4u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_dataid, FZC_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 25u,    4u,     4u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_alivecounter, FZC_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 26u,    8u,     8u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_crc8, FZC_SIG_ICU_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 27u,   16u,     8u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_alivecounter, FZC_SIG_ICU_HEARTBEAT_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 28u,   24u,     8u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_ecu_id, FZC_SIG_ICU_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 29u,    0u,     4u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_dataid, FZC_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 30u,    4u,     4u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_alivecounter, FZC_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 31u,    8u,     8u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_crc8, FZC_SIG_TCU_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 32u,   16u,     8u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_alivecounter, FZC_SIG_TCU_HEARTBEAT_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 33u,   24u,     8u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_ecu_id, FZC_SIG_TCU_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 34u,    0u,     4u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_dataid, FZC_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 35u,    4u,     4u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_alivecounter, FZC_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 36u,    8u,     8u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_crc8, FZC_SIG_BCM_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 37u,   16u,     8u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_alivecounter, FZC_SIG_BCM_HEARTBEAT_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 38u,   24u,     8u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_ecu_id, FZC_SIG_BCM_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 39u,    0u,     4u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_dataid, FZC_SIG_VEHICLE_STATE_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 40u,    4u,     4u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_alivecounter, FZC_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 41u,    8u,     8u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_crc8, FZC_SIG_VEHICLE_STATE_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 42u,   16u,     4u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_mode, FZC_SIG_VEHICLE_STATE_MODE, COM_NO_UPDATE_BIT },
    { 43u,   20u,    12u, COM_UINT16, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_faultmask, FZC_SIG_VEHICLE_STATE_FAULT_MASK, COM_NO_UPDATE_BIT },
    { 44u,   32u,     8u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_torquelimit, FZC_SIG_VEHICLE_STATE_TORQUE_LIMIT, COM_NO_UPDATE_BIT },
    { 45u,   40u,     8u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_speedlimit, FZC_SIG_VEHICLE_STATE_SPEED_LIMIT, COM_NO_UPDATE_BIT },
    { 46u,    0u,     4u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_dataid, FZC_SIG_TORQUE_REQUEST_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 47u,    4u,     4u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_alivecounter, FZC_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 48u,    8u,     8u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_crc8, FZC_SIG_TORQUE_REQUEST_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 49u,   16u,     8u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_command_pct, FZC_SIG_TORQUE_REQUEST_COMMAND_PCT, COM_NO_UPDATE_BIT },
    { 50u,   24u,     2u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_direction, FZC_SIG_TORQUE_REQUEST_DIRECTION, COM_NO_UPDATE_BIT },
    { 51u,   26u,    14u, COM_UINT16, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalposition1, FZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1, COM_NO_UPDATE_BIT },
    { 52u,   40u,    14u, COM_UINT16, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalposition2, FZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2, COM_NO_UPDATE_BIT },
    { 53u,   54u,     1u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalfault, FZC_SIG_TORQUE_REQUEST_PEDAL_FAULT, COM_NO_UPDATE_BIT },
    { 54u,    0u,     4u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_dataid, FZC_SIG_STEER_COMMAND_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 55u,    4u,     4u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_alivecounter, FZC_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 56u,    8u,     8u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_crc8, FZC_SIG_STEER_COMMAND_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 57u,   16u,    16u, COM_UINT16, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_steeranglecmd, FZC_SIG_STEER_COMMAND_STEER_ANGLE_CMD, COM_NO_UPDATE_BIT },
    { 58u,   32u,     8u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_steerratelimit, FZC_SIG_STEER_COMMAND_STEER_RATE_LIMIT, COM_NO_UPDATE_BIT },
    { 59u,   40u,     4u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_vehiclestate, FZC_SIG_STEER_COMMAND_VEHICLE_STATE, COM_NO_UPDATE_BIT },
    { 60u,    0u,     4u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_dataid, FZC_SIG_BRAKE_COMMAND_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 61u,    4u,     4u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_alivecounter, FZC_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 62u,    8u,     8u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_crc8, FZC_SIG_BRAKE_COMMAND_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 63u,   16u,     8u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_brakeforcecmd, FZC_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD, COM_NO_UPDATE_BIT },
    { 64u,   24u,     4u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_brakemode, FZC_SIG_BRAKE_COMMAND_BRAKE_MODE, COM_NO_UPDATE_BIT },
    { 65u,   28u,     4u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_vehiclestate, FZC_SIG_BRAKE_COMMAND_VEHICLE_STATE, COM_NO_UPDATE_BIT },
    { 66u,    0u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_e2e_dataid, FZC_SIG_MOTOR_STATUS_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 67u,    4u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_e2e_alivecounter, FZC_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 68u,    8u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_e2e_crc8, FZC_SIG_MOTOR_STATUS_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 69u,   16u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_torqueecho, FZC_SIG_MOTOR_STATUS_TORQUE_ECHO, COM_NO_UPDATE_BIT },
    { 70u,   24u,    16u, COM_UINT16, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_motorspeed_rpm, FZC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM, COM_NO_UPDATE_BIT },
    { 71u,   40u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_motordirection, FZC_SIG_MOTOR_STATUS_MOTOR_DIRECTION, COM_NO_UPDATE_BIT },
    { 72u,   48u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_motorenable, FZC_SIG_MOTOR_STATUS_MOTOR_ENABLE, COM_NO_UPDATE_BIT },
    { 73u,   56u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_motorfaultstatus, FZC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 74u,    0u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_e2e_dataid, FZC_SIG_MOTOR_CURRENT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 75u,    4u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_e2e_alivecounter, FZC_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 76u,    8u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_e2e_crc8, FZC_SIG_MOTOR_CURRENT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 77u,   16u,    16u, COM_UINT16, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_phase_ma, FZC_SIG_MOTOR_CURRENT_PHASE_M_A, COM_NO_UPDATE_BIT },
    { 78u,   32u,     1u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_dirisreverse, FZC_SIG_MOTOR_CURRENT_DIR_IS_REVERSE, COM_NO_UPDATE_BIT },
    { 79u,   33u,     1u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_motorenable, FZC_SIG_MOTOR_CURRENT_MOTOR_ENABLE, COM_NO_UPDATE_BIT },
    { 80u,   34u,     1u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_overcurrentflag, FZC_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG, COM_NO_UPDATE_BIT },
    { 81u,   35u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_torqueecho, FZC_SIG_MOTOR_CURRENT_TORQUE_ECHO, COM_NO_UPDATE_BIT },
    { 82u,    0u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_e2e_dataid, FZC_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 83u,    4u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_e2e_alivecounter, FZC_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 84u,    8u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_e2e_crc8, FZC_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 85u,   16u,    16u, COM_UINT16, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_windingtemp1_c, FZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C, COM_NO_UPDATE_BIT },
    { 86u,   32u,    16u, COM_UINT16, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_windingtemp2_c, FZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C, COM_NO_UPDATE_BIT },
    { 87u,   48u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_deratingpercent, FZC_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT, COM_NO_UPDATE_BIT },
    { 88u,    0u,     4u, COM_UINT8, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_e2e_dataid, FZC_SIG_BATTERY_STATUS_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 89u,    4u,     4u, COM_UINT8, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_e2e_alivecounter, FZC_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 90u,    8u,     8u, COM_UINT8, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_e2e_crc8, FZC_SIG_BATTERY_STATUS_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 91u,   16u,    16u, COM_UINT16, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_batteryvoltage_mv, FZC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V, COM_NO_UPDATE_BIT },
    { 92u,   32u,     8u, COM_UINT8, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_level, FZC_SIG_BATTERY_STATUS_LEVEL, COM_NO_UPDATE_BIT },
    { 93u,    0u,     2u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_headlightcmd, FZC_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD, COM_NO_UPDATE_BIT },
    { 94u,    2u,     1u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_taillighton, FZC_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_ON, COM_NO_UPDATE_BIT },
    { 95u,    3u,     1u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_hazardactive, FZC_SIG_BODY_CONTROL_CMD_HAZARD_ACTIVE, COM_NO_UPDATE_BIT },
    { 96u,    4u,     2u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_turnsignalcmd, FZC_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD, COM_NO_UPDATE_BIT },
    { 97u,    6u,     1u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_doorlockcmd, FZC_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD, COM_NO_UPDATE_BIT },
    { 98u,    0u,     1u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_headlighton, FZC_SIG_LIGHT_STATUS_HEADLIGHT_ON, COM_NO_UPDATE_BIT },
    { 99u,    1u,     1u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_taillighton, FZC_SIG_LIGHT_STATUS_TAIL_LIGHT_ON, COM_NO_UPDATE_BIT },
    { 100u,    2u,     1u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_foglighton, FZC_SIG_LIGHT_STATUS_FOG_LIGHT_ON, COM_NO_UPDATE_BIT },
    { 101u,    3u,     1u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_brakelighton, FZC_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON, COM_NO_UPDATE_BIT },
    { 102u,    4u,     2u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_headlightlevel, FZC_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL, COM_NO_UPDATE_BIT },
    { 103u,    0u,     1u, COM_UINT8, FZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_lefton, FZC_SIG_INDICATOR_STATE_LEFT_ON, COM_NO_UPDATE_BIT },
    { 104u,    1u,     1u, COM_UINT8, FZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_righton, FZC_SIG_INDICATOR_STATE_RIGHT_ON, COM_NO_UPDATE_BIT },
    { 105u,    2u,     1u, COM_UINT8, FZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_hazardactive, FZC_SIG_INDICATOR_STATE_HAZARD_ACTIVE, COM_NO_UPDATE_BIT },
    { 106u,    3u,     1u, COM_UINT8, FZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_blinkphasehigh, FZC_SIG_INDICATOR_STATE_BLINK_PHASE_HIGH, COM_NO_UPDATE_BIT },
    { 107u,    0u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_frontleftlock, FZC_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK, COM_NO_UPDATE_BIT },
    { 108u,    1u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_frontrightlock, FZC_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK, COM_NO_UPDATE_BIT },
    { 109u,    2u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_rearleftlock, FZC_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK, COM_NO_UPDATE_BIT },
    { 110u,    3u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_rearrightlock, FZC_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK, COM_NO_UPDATE_BIT },
    { 111u,    4u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_centrallock, FZC_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK, COM_NO_UPDATE_BIT },
    { 112u,    7u,    16u, COM_UINT16, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_number, FZC_SIG_DTC_BROADCAST_NUMBER, COM_NO_UPDATE_BIT },
    { 113u,   24u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_status, FZC_SIG_DTC_BROADCAST_STATUS, COM_NO_UPDATE_BIT },
    { 114u,   32u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_ecu_source, FZC_SIG_DTC_BROADCAST_ECU_SOURCE, COM_NO_UPDATE_BIT },
    { 115u,   40u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_occurrencecount, FZC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT, COM_NO_UPDATE_BIT },
    { 116u,   48u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_freezeframe0, FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_0, COM_NO_UPDATE_BIT },
    { 117u,   56u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_freezeframe1, FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_1, COM_NO_UPDATE_BIT },
    { 118u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_REQ_CVC, &sig_rx_xcp_req_cvc_data, FZC_SIG_XCP_REQ_CVC_DATA, COM_NO_UPDATE_BIT },
    { 119u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_RESP_CVC, &sig_rx_xcp_resp_cvc_data, FZC_SIG_XCP_RESP_CVC_DATA, COM_NO_UPDATE_BIT },
    { 120u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_REQ_FZC, &sig_rx_xcp_req_fzc_data, FZC_SIG_XCP_REQ_FZC_DATA, COM_NO_UPDATE_BIT },
    { 121u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_REQ_RZC, &sig_rx_xcp_req_rzc_data, FZC_SIG_XCP_REQ_RZC_DATA, COM_NO_UPDATE_BIT },
    { 122u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_RESP_RZC, &sig_rx_xcp_resp_rzc_data, FZC_SIG_XCP_RESP_RZC_DATA, COM_NO_UPDATE_BIT },
    { 123u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_REQ_SC, &sig_rx_xcp_req_sc_data, FZC_SIG_XCP_REQ_SC_DATA, COM_NO_UPDATE_BIT },
    { 124u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_RESP_SC, &sig_rx_xcp_resp_sc_data, FZC_SIG_XCP_RESP_SC_DATA, COM_NO_UPDATE_BIT },
    { 125u,    0u,    16u, COM_UINT16, FZC_COM_RX_FZC_VIRTUAL_SENSORS, &sig_rx_fzc_virtual_sensors_steerangle_raw, FZC_SIG_FZC_VIRTUAL_SENSORS_STEER_ANGLE_RAW, COM_NO_UPDATE_BIT },
    { 126u,   16u,    16u, COM_UINT16, FZC_COM_RX_FZC_VIRTUAL_SENSORS, &sig_rx_fzc_virtual_sensors_brakepos_adc, FZC_SIG_FZC_VIRTUAL_SENSORS_BRAKE_POS_ADC, COM_NO_UPDATE_BIT },
    { 127u,   32u,    16u, COM_UINT16, FZC_COM_RX_FZC_VIRTUAL_SENSORS, &sig_rx_fzc_virtual_sensors_brakecurrent_ma, FZC_SIG_FZC_VIRTUAL_SENSORS_BRAKE_CURRENT_M_A, COM_NO_UPDATE_BIT },
    { 128u,    0u,    16u, COM_UINT16, FZC_COM_RX_RZC_VIRTUAL_SENSORS, &sig_rx_rzc_virtual_sensors_motorcurrent_ma, FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_CURRENT_M_A, COM_NO_UPDATE_BIT },
    { 129u,   16u,    16u, COM_UINT16, FZC_COM_RX_RZC_VIRTUAL_SENSORS, &sig_rx_rzc_virtual_sensors_motortemp_dc, FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_TEMP_D_C, COM_NO_UPDATE_BIT },
    { 130u,   32u,    16u, COM_UINT16, FZC_COM_RX_RZC_VIRTUAL_SENSORS, &sig_rx_rzc_virtual_sensors_battvoltage_mv, FZC_SIG_RZC_VIRTUAL_SENSORS_BATT_VOLTAGE_M_V, COM_NO_UPDATE_BIT },
    { 131u,   48u,    16u, COM_UINT16, FZC_COM_RX_RZC_VIRTUAL_SENSORS, &sig_rx_rzc_virtual_sensors_motorspeed_rpm, FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_SPEED_RPM, COM_NO_UPDATE_BIT },
    { 132u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_RESP_TCU, &sig_rx_uds_resp_tcu_uds_data, FZC_SIG_UDS_RESP_TCU_UDS_DATA, COM_NO_UPDATE_BIT },
    { 133u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_FUNC_REQUEST, &sig_rx_uds_func_request_uds_data, FZC_SIG_UDS_FUNC_REQUEST_UDS_DATA, COM_NO_UPDATE_BIT },
    { 134u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_PHYS_REQ_CVC, &sig_rx_uds_phys_req_cvc_uds_data, FZC_SIG_UDS_PHYS_REQ_CVC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 135u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_PHYS_REQ_FZC, &sig_rx_uds_phys_req_fzc_uds_data, FZC_SIG_UDS_PHYS_REQ_FZC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 136u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_PHYS_REQ_RZC, &sig_rx_uds_phys_req_rzc_uds_data, FZC_SIG_UDS_PHYS_REQ_RZC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 137u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_PHYS_REQ_TCU, &sig_rx_uds_phys_req_tcu_uds_data, FZC_SIG_UDS_PHYS_REQ_TCU_UDS_DATA, COM_NO_UPDATE_BIT },
    { 138u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_RESP_CVC, &sig_rx_uds_resp_cvc_uds_data, FZC_SIG_UDS_RESP_CVC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 139u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_RESP_RZC, &sig_rx_uds_resp_rzc_uds_data, FZC_SIG_UDS_RESP_RZC_UDS_DATA, COM_NO_UPDATE_BIT },
};

#define FZC_COM_RX_SIGNAL_COUNT  (sizeof(fzc_rx_signal_config) / sizeof(fzc_rx_signal_config[0]))

/* Legacy combined table — used by Com_SendSignal / Com_ReceiveSignal.
 * TX signals first (indexed by FZC_COM_SIG_* TX defines), then RX signals.
 * TODO: migrate SWC code to Rte_Write/Rte_Read and remove this table. */
static const Com_SignalConfigType fzc_signal_config[] = {
    {  0u,    0u,     4u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  1u,    4u,     4u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  2u,    8u,     8u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  3u,   16u,     8u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_ecu_id, FZC_SIG_FZC_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    {  4u,   24u,     4u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_operatingmode, FZC_SIG_FZC_HEARTBEAT_OPERATING_MODE, COM_NO_UPDATE_BIT },
    {  5u,   28u,     4u, COM_UINT8, FZC_COM_TX_FZC_HEARTBEAT, &sig_tx_fzc_heartbeat_faultstatus, FZC_SIG_FZC_HEARTBEAT_FAULT_STATUS, COM_NO_UPDATE_BIT },
    {  6u,    0u,     4u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  7u,    4u,     4u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  8u,    8u,     8u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    {  9u,   16u,    16u, COM_UINT16, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_actualangle, FZC_SIG_STEERING_STATUS_ACTUAL_ANGLE, COM_NO_UPDATE_BIT },
    { 10u,   32u,    16u, COM_UINT16, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_commandedangle, FZC_SIG_STEERING_STATUS_COMMANDED_ANGLE, COM_NO_UPDATE_BIT },
    { 11u,   48u,     4u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_steerfaultstatus, FZC_SIG_STEERING_STATUS_STEER_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 12u,   52u,     4u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_steermode, FZC_SIG_STEERING_STATUS_STEER_MODE, COM_NO_UPDATE_BIT },
    { 13u,   56u,     8u, COM_UINT8, FZC_COM_TX_STEERING_STATUS, &sig_tx_steering_status_servocurrent_ma, FZC_SIG_STEERING_STATUS_SERVO_CURRENT_M_A, COM_NO_UPDATE_BIT },
    { 14u,    0u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 15u,    4u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 16u,    8u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 17u,   16u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_brakeposition, FZC_SIG_BRAKE_STATUS_BRAKE_POSITION, COM_NO_UPDATE_BIT },
    { 18u,   24u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_brakecommandecho, FZC_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO, COM_NO_UPDATE_BIT },
    { 19u,   32u,    16u, COM_UINT16, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_servocurrent_ma, FZC_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A, COM_NO_UPDATE_BIT },
    { 20u,   48u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_brakefaultstatus, FZC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 21u,   52u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_STATUS, &sig_tx_brake_status_brakemode, FZC_SIG_BRAKE_STATUS_BRAKE_MODE, COM_NO_UPDATE_BIT },
    { 22u,    0u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 23u,    4u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 24u,    8u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 25u,   16u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_faulttype, FZC_SIG_BRAKE_FAULT_FAULT_TYPE, COM_NO_UPDATE_BIT },
    { 26u,   20u,     8u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_commandedbrake, FZC_SIG_BRAKE_FAULT_COMMANDED_BRAKE, COM_NO_UPDATE_BIT },
    { 27u,   28u,     4u, COM_UINT8, FZC_COM_TX_BRAKE_FAULT, &sig_tx_brake_fault_measuredbrake, FZC_SIG_BRAKE_FAULT_MEASURED_BRAKE, COM_NO_UPDATE_BIT },
    { 28u,    0u,     4u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 29u,    4u,     4u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 30u,    8u,     8u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 31u,   16u,     4u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_requesttype, FZC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE, COM_NO_UPDATE_BIT },
    { 32u,   20u,     4u, COM_UINT8, FZC_COM_TX_MOTOR_CUTOFF_REQ, &sig_tx_motor_cutoff_req_reason, FZC_SIG_MOTOR_CUTOFF_REQ_REASON, COM_NO_UPDATE_BIT },
    { 33u,    0u,     4u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_e2e_dataid, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 34u,    4u,     4u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_e2e_alivecounter, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 35u,    8u,     8u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_e2e_crc8, COM_RTE_SIGNAL_NONE, COM_NO_UPDATE_BIT },
    { 36u,   16u,    16u, COM_UINT16, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_range_cm, FZC_SIG_LIDAR_DISTANCE_RANGE_CM, COM_NO_UPDATE_BIT },
    { 37u,   32u,    16u, COM_UINT16, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_signalstrength, FZC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH, COM_NO_UPDATE_BIT },
    { 38u,   48u,     4u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_obstaclezone, FZC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE, COM_NO_UPDATE_BIT },
    { 39u,   52u,     4u, COM_UINT8, FZC_COM_TX_LIDAR_DISTANCE, &sig_tx_lidar_distance_sensorstatus, FZC_SIG_LIDAR_DISTANCE_SENSOR_STATUS, COM_NO_UPDATE_BIT },
    { 40u,    7u,    16u, COM_UINT16, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_number, FZC_SIG_DTC_BROADCAST_NUMBER, COM_NO_UPDATE_BIT },
    { 41u,   24u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_status, FZC_SIG_DTC_BROADCAST_STATUS, COM_NO_UPDATE_BIT },
    { 42u,   32u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_ecu_source, FZC_SIG_DTC_BROADCAST_ECU_SOURCE, COM_NO_UPDATE_BIT },
    { 43u,   40u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_occurrencecount, FZC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT, COM_NO_UPDATE_BIT },
    { 44u,   48u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_freezeframe0, FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_0, COM_NO_UPDATE_BIT },
    { 45u,   56u,     8u, COM_UINT8, FZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_freezeframe1, FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_1, COM_NO_UPDATE_BIT },
    { 46u,    0u,    64u, COM_UINT32, FZC_COM_TX_XCP_RESP_FZC, &sig_tx_xcp_resp_fzc_data, FZC_SIG_XCP_RESP_FZC_DATA, COM_NO_UPDATE_BIT },
    { 47u,    0u,    64u, COM_UINT32, FZC_COM_TX_UDS_RESP_FZC, &sig_tx_uds_resp_fzc_uds_data, FZC_SIG_UDS_RESP_FZC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 48u,    0u,     4u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_dataid, FZC_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 49u,    4u,     4u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_alivecounter, FZC_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 50u,    8u,     8u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_crc8, FZC_SIG_ESTOP_BROADCAST_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 51u,   16u,     8u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_active, FZC_SIG_ESTOP_BROADCAST_ACTIVE, COM_NO_UPDATE_BIT },
    { 52u,   24u,     8u, COM_UINT8, FZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_source, FZC_SIG_ESTOP_BROADCAST_SOURCE, COM_NO_UPDATE_BIT },
    { 53u,    0u,     4u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_dataid, FZC_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 54u,    4u,     4u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_alivecounter, FZC_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 55u,    8u,     8u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_crc8, FZC_SIG_CVC_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 56u,   16u,     8u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_ecu_id, FZC_SIG_CVC_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 57u,   24u,     4u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_operatingmode, FZC_SIG_CVC_HEARTBEAT_OPERATING_MODE, COM_NO_UPDATE_BIT },
    { 58u,   28u,     4u, COM_UINT8, FZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_faultstatus, FZC_SIG_CVC_HEARTBEAT_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 59u,    0u,     4u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_e2e_dataid, FZC_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 60u,    4u,     4u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_e2e_alivecounter, FZC_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 61u,    8u,     8u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_e2e_crc8, FZC_SIG_RZC_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 62u,   16u,     8u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_ecu_id, FZC_SIG_RZC_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 63u,   24u,     4u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_operatingmode, FZC_SIG_RZC_HEARTBEAT_OPERATING_MODE, COM_NO_UPDATE_BIT },
    { 64u,   28u,     4u, COM_UINT8, FZC_COM_RX_RZC_HEARTBEAT, &sig_rx_rzc_heartbeat_faultstatus, FZC_SIG_RZC_HEARTBEAT_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 65u,    0u,     8u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_alivecounter, FZC_SIG_SC_STATUS_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 66u,    8u,     8u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_crc8, FZC_SIG_SC_STATUS_CRC_8, COM_NO_UPDATE_BIT },
    { 67u,   16u,     4u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_mode, FZC_SIG_SC_STATUS_MODE, COM_NO_UPDATE_BIT },
    { 68u,   20u,     4u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_faultflags, FZC_SIG_SC_STATUS_FAULT_FLAGS, COM_NO_UPDATE_BIT },
    { 69u,   24u,     3u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_ecu_health, FZC_SIG_SC_STATUS_ECU_HEALTH, COM_NO_UPDATE_BIT },
    { 70u,   27u,     4u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_faultreason, FZC_SIG_SC_STATUS_FAULT_REASON, COM_NO_UPDATE_BIT },
    { 71u,   31u,     1u, COM_UINT8, FZC_COM_RX_SC_STATUS, &sig_rx_sc_status_relayenergized, FZC_SIG_SC_STATUS_RELAY_ENERGIZED, COM_NO_UPDATE_BIT },
    { 72u,    0u,     4u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_dataid, FZC_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 73u,    4u,     4u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_alivecounter, FZC_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 74u,    8u,     8u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_crc8, FZC_SIG_ICU_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 75u,   16u,     8u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_alivecounter, FZC_SIG_ICU_HEARTBEAT_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 76u,   24u,     8u, COM_UINT8, FZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_ecu_id, FZC_SIG_ICU_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 77u,    0u,     4u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_dataid, FZC_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 78u,    4u,     4u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_alivecounter, FZC_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 79u,    8u,     8u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_crc8, FZC_SIG_TCU_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 80u,   16u,     8u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_alivecounter, FZC_SIG_TCU_HEARTBEAT_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 81u,   24u,     8u, COM_UINT8, FZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_ecu_id, FZC_SIG_TCU_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 82u,    0u,     4u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_dataid, FZC_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 83u,    4u,     4u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_alivecounter, FZC_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 84u,    8u,     8u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_crc8, FZC_SIG_BCM_HEARTBEAT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 85u,   16u,     8u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_alivecounter, FZC_SIG_BCM_HEARTBEAT_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 86u,   24u,     8u, COM_UINT8, FZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_ecu_id, FZC_SIG_BCM_HEARTBEAT_ECU_ID, COM_NO_UPDATE_BIT },
    { 87u,    0u,     4u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_dataid, FZC_SIG_VEHICLE_STATE_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 88u,    4u,     4u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_alivecounter, FZC_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 89u,    8u,     8u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_crc8, FZC_SIG_VEHICLE_STATE_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 90u,   16u,     4u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_mode, FZC_SIG_VEHICLE_STATE_MODE, COM_NO_UPDATE_BIT },
    { 91u,   20u,    12u, COM_UINT16, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_faultmask, FZC_SIG_VEHICLE_STATE_FAULT_MASK, COM_NO_UPDATE_BIT },
    { 92u,   32u,     8u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_torquelimit, FZC_SIG_VEHICLE_STATE_TORQUE_LIMIT, COM_NO_UPDATE_BIT },
    { 93u,   40u,     8u, COM_UINT8, FZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_speedlimit, FZC_SIG_VEHICLE_STATE_SPEED_LIMIT, COM_NO_UPDATE_BIT },
    { 94u,    0u,     4u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_dataid, FZC_SIG_TORQUE_REQUEST_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 95u,    4u,     4u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_alivecounter, FZC_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 96u,    8u,     8u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_crc8, FZC_SIG_TORQUE_REQUEST_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 97u,   16u,     8u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_command_pct, FZC_SIG_TORQUE_REQUEST_COMMAND_PCT, COM_NO_UPDATE_BIT },
    { 98u,   24u,     2u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_direction, FZC_SIG_TORQUE_REQUEST_DIRECTION, COM_NO_UPDATE_BIT },
    { 99u,   26u,    14u, COM_UINT16, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalposition1, FZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1, COM_NO_UPDATE_BIT },
    { 100u,   40u,    14u, COM_UINT16, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalposition2, FZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2, COM_NO_UPDATE_BIT },
    { 101u,   54u,     1u, COM_UINT8, FZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalfault, FZC_SIG_TORQUE_REQUEST_PEDAL_FAULT, COM_NO_UPDATE_BIT },
    { 102u,    0u,     4u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_dataid, FZC_SIG_STEER_COMMAND_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 103u,    4u,     4u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_alivecounter, FZC_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 104u,    8u,     8u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_crc8, FZC_SIG_STEER_COMMAND_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 105u,   16u,    16u, COM_UINT16, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_steeranglecmd, FZC_SIG_STEER_COMMAND_STEER_ANGLE_CMD, COM_NO_UPDATE_BIT },
    { 106u,   32u,     8u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_steerratelimit, FZC_SIG_STEER_COMMAND_STEER_RATE_LIMIT, COM_NO_UPDATE_BIT },
    { 107u,   40u,     4u, COM_UINT8, FZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_vehiclestate, FZC_SIG_STEER_COMMAND_VEHICLE_STATE, COM_NO_UPDATE_BIT },
    { 108u,    0u,     4u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_dataid, FZC_SIG_BRAKE_COMMAND_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 109u,    4u,     4u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_alivecounter, FZC_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 110u,    8u,     8u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_crc8, FZC_SIG_BRAKE_COMMAND_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 111u,   16u,     8u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_brakeforcecmd, FZC_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD, COM_NO_UPDATE_BIT },
    { 112u,   24u,     4u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_brakemode, FZC_SIG_BRAKE_COMMAND_BRAKE_MODE, COM_NO_UPDATE_BIT },
    { 113u,   28u,     4u, COM_UINT8, FZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_vehiclestate, FZC_SIG_BRAKE_COMMAND_VEHICLE_STATE, COM_NO_UPDATE_BIT },
    { 114u,    0u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_e2e_dataid, FZC_SIG_MOTOR_STATUS_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 115u,    4u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_e2e_alivecounter, FZC_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 116u,    8u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_e2e_crc8, FZC_SIG_MOTOR_STATUS_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 117u,   16u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_torqueecho, FZC_SIG_MOTOR_STATUS_TORQUE_ECHO, COM_NO_UPDATE_BIT },
    { 118u,   24u,    16u, COM_UINT16, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_motorspeed_rpm, FZC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM, COM_NO_UPDATE_BIT },
    { 119u,   40u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_motordirection, FZC_SIG_MOTOR_STATUS_MOTOR_DIRECTION, COM_NO_UPDATE_BIT },
    { 120u,   48u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_motorenable, FZC_SIG_MOTOR_STATUS_MOTOR_ENABLE, COM_NO_UPDATE_BIT },
    { 121u,   56u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_STATUS, &sig_rx_motor_status_motorfaultstatus, FZC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS, COM_NO_UPDATE_BIT },
    { 122u,    0u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_e2e_dataid, FZC_SIG_MOTOR_CURRENT_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 123u,    4u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_e2e_alivecounter, FZC_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 124u,    8u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_e2e_crc8, FZC_SIG_MOTOR_CURRENT_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 125u,   16u,    16u, COM_UINT16, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_phase_ma, FZC_SIG_MOTOR_CURRENT_PHASE_M_A, COM_NO_UPDATE_BIT },
    { 126u,   32u,     1u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_dirisreverse, FZC_SIG_MOTOR_CURRENT_DIR_IS_REVERSE, COM_NO_UPDATE_BIT },
    { 127u,   33u,     1u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_motorenable, FZC_SIG_MOTOR_CURRENT_MOTOR_ENABLE, COM_NO_UPDATE_BIT },
    { 128u,   34u,     1u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_overcurrentflag, FZC_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG, COM_NO_UPDATE_BIT },
    { 129u,   35u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_CURRENT, &sig_rx_motor_current_torqueecho, FZC_SIG_MOTOR_CURRENT_TORQUE_ECHO, COM_NO_UPDATE_BIT },
    { 130u,    0u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_e2e_dataid, FZC_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 131u,    4u,     4u, COM_UINT8, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_e2e_alivecounter, FZC_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 132u,    8u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_e2e_crc8, FZC_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 133u,   16u,    16u, COM_UINT16, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_windingtemp1_c, FZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C, COM_NO_UPDATE_BIT },
    { 134u,   32u,    16u, COM_UINT16, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_windingtemp2_c, FZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C, COM_NO_UPDATE_BIT },
    { 135u,   48u,     8u, COM_UINT8, FZC_COM_RX_MOTOR_TEMPERATURE, &sig_rx_motor_temperature_deratingpercent, FZC_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT, COM_NO_UPDATE_BIT },
    { 136u,    0u,     4u, COM_UINT8, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_e2e_dataid, FZC_SIG_BATTERY_STATUS_E_2_E_DATA_ID, COM_NO_UPDATE_BIT },
    { 137u,    4u,     4u, COM_UINT8, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_e2e_alivecounter, FZC_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER, COM_NO_UPDATE_BIT },
    { 138u,    8u,     8u, COM_UINT8, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_e2e_crc8, FZC_SIG_BATTERY_STATUS_E_2_E_CRC_8, COM_NO_UPDATE_BIT },
    { 139u,   16u,    16u, COM_UINT16, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_batteryvoltage_mv, FZC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V, COM_NO_UPDATE_BIT },
    { 140u,   32u,     8u, COM_UINT8, FZC_COM_RX_BATTERY_STATUS, &sig_rx_battery_status_level, FZC_SIG_BATTERY_STATUS_LEVEL, COM_NO_UPDATE_BIT },
    { 141u,    0u,     2u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_headlightcmd, FZC_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD, COM_NO_UPDATE_BIT },
    { 142u,    2u,     1u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_taillighton, FZC_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_ON, COM_NO_UPDATE_BIT },
    { 143u,    3u,     1u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_hazardactive, FZC_SIG_BODY_CONTROL_CMD_HAZARD_ACTIVE, COM_NO_UPDATE_BIT },
    { 144u,    4u,     2u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_turnsignalcmd, FZC_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD, COM_NO_UPDATE_BIT },
    { 145u,    6u,     1u, COM_UINT8, FZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_doorlockcmd, FZC_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD, COM_NO_UPDATE_BIT },
    { 146u,    0u,     1u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_headlighton, FZC_SIG_LIGHT_STATUS_HEADLIGHT_ON, COM_NO_UPDATE_BIT },
    { 147u,    1u,     1u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_taillighton, FZC_SIG_LIGHT_STATUS_TAIL_LIGHT_ON, COM_NO_UPDATE_BIT },
    { 148u,    2u,     1u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_foglighton, FZC_SIG_LIGHT_STATUS_FOG_LIGHT_ON, COM_NO_UPDATE_BIT },
    { 149u,    3u,     1u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_brakelighton, FZC_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON, COM_NO_UPDATE_BIT },
    { 150u,    4u,     2u, COM_UINT8, FZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_headlightlevel, FZC_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL, COM_NO_UPDATE_BIT },
    { 151u,    0u,     1u, COM_UINT8, FZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_lefton, FZC_SIG_INDICATOR_STATE_LEFT_ON, COM_NO_UPDATE_BIT },
    { 152u,    1u,     1u, COM_UINT8, FZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_righton, FZC_SIG_INDICATOR_STATE_RIGHT_ON, COM_NO_UPDATE_BIT },
    { 153u,    2u,     1u, COM_UINT8, FZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_hazardactive, FZC_SIG_INDICATOR_STATE_HAZARD_ACTIVE, COM_NO_UPDATE_BIT },
    { 154u,    3u,     1u, COM_UINT8, FZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_blinkphasehigh, FZC_SIG_INDICATOR_STATE_BLINK_PHASE_HIGH, COM_NO_UPDATE_BIT },
    { 155u,    0u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_frontleftlock, FZC_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK, COM_NO_UPDATE_BIT },
    { 156u,    1u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_frontrightlock, FZC_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK, COM_NO_UPDATE_BIT },
    { 157u,    2u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_rearleftlock, FZC_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK, COM_NO_UPDATE_BIT },
    { 158u,    3u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_rearrightlock, FZC_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK, COM_NO_UPDATE_BIT },
    { 159u,    4u,     1u, COM_UINT8, FZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_centrallock, FZC_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK, COM_NO_UPDATE_BIT },
    { 160u,    7u,    16u, COM_UINT16, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_number, FZC_SIG_DTC_BROADCAST_NUMBER, COM_NO_UPDATE_BIT },
    { 161u,   24u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_status, FZC_SIG_DTC_BROADCAST_STATUS, COM_NO_UPDATE_BIT },
    { 162u,   32u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_ecu_source, FZC_SIG_DTC_BROADCAST_ECU_SOURCE, COM_NO_UPDATE_BIT },
    { 163u,   40u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_occurrencecount, FZC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT, COM_NO_UPDATE_BIT },
    { 164u,   48u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_freezeframe0, FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_0, COM_NO_UPDATE_BIT },
    { 165u,   56u,     8u, COM_UINT8, FZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_freezeframe1, FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_1, COM_NO_UPDATE_BIT },
    { 166u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_REQ_CVC, &sig_rx_xcp_req_cvc_data, FZC_SIG_XCP_REQ_CVC_DATA, COM_NO_UPDATE_BIT },
    { 167u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_RESP_CVC, &sig_rx_xcp_resp_cvc_data, FZC_SIG_XCP_RESP_CVC_DATA, COM_NO_UPDATE_BIT },
    { 168u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_REQ_FZC, &sig_rx_xcp_req_fzc_data, FZC_SIG_XCP_REQ_FZC_DATA, COM_NO_UPDATE_BIT },
    { 169u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_REQ_RZC, &sig_rx_xcp_req_rzc_data, FZC_SIG_XCP_REQ_RZC_DATA, COM_NO_UPDATE_BIT },
    { 170u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_RESP_RZC, &sig_rx_xcp_resp_rzc_data, FZC_SIG_XCP_RESP_RZC_DATA, COM_NO_UPDATE_BIT },
    { 171u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_REQ_SC, &sig_rx_xcp_req_sc_data, FZC_SIG_XCP_REQ_SC_DATA, COM_NO_UPDATE_BIT },
    { 172u,    0u,    64u, COM_UINT32, FZC_COM_RX_XCP_RESP_SC, &sig_rx_xcp_resp_sc_data, FZC_SIG_XCP_RESP_SC_DATA, COM_NO_UPDATE_BIT },
    { 173u,    0u,    16u, COM_UINT16, FZC_COM_RX_FZC_VIRTUAL_SENSORS, &sig_rx_fzc_virtual_sensors_steerangle_raw, FZC_SIG_FZC_VIRTUAL_SENSORS_STEER_ANGLE_RAW, COM_NO_UPDATE_BIT },
    { 174u,   16u,    16u, COM_UINT16, FZC_COM_RX_FZC_VIRTUAL_SENSORS, &sig_rx_fzc_virtual_sensors_brakepos_adc, FZC_SIG_FZC_VIRTUAL_SENSORS_BRAKE_POS_ADC, COM_NO_UPDATE_BIT },
    { 175u,   32u,    16u, COM_UINT16, FZC_COM_RX_FZC_VIRTUAL_SENSORS, &sig_rx_fzc_virtual_sensors_brakecurrent_ma, FZC_SIG_FZC_VIRTUAL_SENSORS_BRAKE_CURRENT_M_A, COM_NO_UPDATE_BIT },
    { 176u,    0u,    16u, COM_UINT16, FZC_COM_RX_RZC_VIRTUAL_SENSORS, &sig_rx_rzc_virtual_sensors_motorcurrent_ma, FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_CURRENT_M_A, COM_NO_UPDATE_BIT },
    { 177u,   16u,    16u, COM_UINT16, FZC_COM_RX_RZC_VIRTUAL_SENSORS, &sig_rx_rzc_virtual_sensors_motortemp_dc, FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_TEMP_D_C, COM_NO_UPDATE_BIT },
    { 178u,   32u,    16u, COM_UINT16, FZC_COM_RX_RZC_VIRTUAL_SENSORS, &sig_rx_rzc_virtual_sensors_battvoltage_mv, FZC_SIG_RZC_VIRTUAL_SENSORS_BATT_VOLTAGE_M_V, COM_NO_UPDATE_BIT },
    { 179u,   48u,    16u, COM_UINT16, FZC_COM_RX_RZC_VIRTUAL_SENSORS, &sig_rx_rzc_virtual_sensors_motorspeed_rpm, FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_SPEED_RPM, COM_NO_UPDATE_BIT },
    { 180u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_RESP_TCU, &sig_rx_uds_resp_tcu_uds_data, FZC_SIG_UDS_RESP_TCU_UDS_DATA, COM_NO_UPDATE_BIT },
    { 181u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_FUNC_REQUEST, &sig_rx_uds_func_request_uds_data, FZC_SIG_UDS_FUNC_REQUEST_UDS_DATA, COM_NO_UPDATE_BIT },
    { 182u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_PHYS_REQ_CVC, &sig_rx_uds_phys_req_cvc_uds_data, FZC_SIG_UDS_PHYS_REQ_CVC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 183u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_PHYS_REQ_FZC, &sig_rx_uds_phys_req_fzc_uds_data, FZC_SIG_UDS_PHYS_REQ_FZC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 184u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_PHYS_REQ_RZC, &sig_rx_uds_phys_req_rzc_uds_data, FZC_SIG_UDS_PHYS_REQ_RZC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 185u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_PHYS_REQ_TCU, &sig_rx_uds_phys_req_tcu_uds_data, FZC_SIG_UDS_PHYS_REQ_TCU_UDS_DATA, COM_NO_UPDATE_BIT },
    { 186u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_RESP_CVC, &sig_rx_uds_resp_cvc_uds_data, FZC_SIG_UDS_RESP_CVC_UDS_DATA, COM_NO_UPDATE_BIT },
    { 187u,    0u,    64u, COM_UINT32, FZC_COM_RX_UDS_RESP_RZC, &sig_rx_uds_resp_rzc_uds_data, FZC_SIG_UDS_RESP_RZC_UDS_DATA, COM_NO_UPDATE_BIT },
};

#define FZC_COM_SIGNAL_COUNT  (sizeof(fzc_signal_config) / sizeof(fzc_signal_config[0]))

/* ==================================================================
 * TX PDU Configuration Table
 * Maps PDU ID -> DLC, cycle time
 * PDU ID to CAN ID routing is handled by CanIf
 * ================================================================== */

static const Com_TxPduConfigType fzc_tx_pdu_config[] = {
    /* pduId,                      dlc, cycleMs, txMode,              e2eProt, dataId, cntBit, crcBit */
    { FZC_COM_TX_FZC_HEARTBEAT,     4u,    50u, COM_TX_MODE_PERIODIC, TRUE ,  3u,  4u,  8u },   /* CAN 0x011 @satisfies SG-008 */
    { FZC_COM_TX_STEERING_STATUS,     8u,    50u, COM_TX_MODE_PERIODIC, TRUE ,  9u,  4u,  8u },   /* CAN 0x200 @satisfies SG-003 */
    { FZC_COM_TX_BRAKE_STATUS,     8u,    50u, COM_TX_MODE_PERIODIC, TRUE , 10u,  4u,  8u },   /* CAN 0x201 @satisfies SG-004 */
    { FZC_COM_TX_BRAKE_FAULT,     4u,     0u, COM_TX_MODE_DIRECT  , TRUE , 11u,  4u,  8u },   /* CAN 0x210 @satisfies SG-004,SG-008 */
    { FZC_COM_TX_MOTOR_CUTOFF_REQ,     4u,     0u, COM_TX_MODE_DIRECT  , TRUE , 12u,  4u,  8u },   /* CAN 0x211 @satisfies SG-008 */
    { FZC_COM_TX_LIDAR_DISTANCE,     8u,    10u, COM_TX_MODE_PERIODIC, TRUE , 13u,  4u,  8u },   /* CAN 0x220 @satisfies SG-007 */
    { FZC_COM_TX_DTC_BROADCAST,     8u,     0u, COM_TX_MODE_DIRECT  , FALSE,  0u,  0u,  8u },   /* CAN 0x500 */
    { FZC_COM_TX_XCP_RESP_FZC,     8u,     0u, COM_TX_MODE_DIRECT  , FALSE,  0u,  0u,  8u },   /* CAN 0x553 */
    { FZC_COM_TX_UDS_RESP_FZC,     8u,     0u, COM_TX_MODE_DIRECT  , FALSE,  0u,  0u,  8u },   /* CAN 0x7E9 */
};

#define FZC_COM_TX_PDU_COUNT  (sizeof(fzc_tx_pdu_config) / sizeof(fzc_tx_pdu_config[0]))

/* ==================================================================
 * RX PDU Configuration Table
 * ================================================================== */

static const Com_RxPduConfigType fzc_rx_pdu_config[] = {
    /* pduId,                     dlc, timeoutMs, e2eProt, dataId, maxDelta, demEvt, smValid, smInvalid, commStatusSigId */
    { FZC_COM_RX_ESTOP_BROADCAST,     4u,    30u, TRUE ,  1u,  3u, COM_DEM_EVENT_NONE, 3u, 10u, COM_RTE_SIGNAL_NONE },   /* CAN 0x001 @satisfies SG-008 */
    { FZC_COM_RX_CVC_HEARTBEAT,     4u,   150u, TRUE ,  2u,  7u, 12, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x010 @satisfies SG-008 */
    { FZC_COM_RX_RZC_HEARTBEAT,     4u,   150u, TRUE ,  4u,  7u, COM_DEM_EVENT_NONE, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x012 @satisfies SG-008 */
    { FZC_COM_RX_SC_STATUS,     4u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x013 @satisfies SG-008 */
    { FZC_COM_RX_ICU_HEARTBEAT,     4u,  1500u, TRUE ,  0u, 14u, COM_DEM_EVENT_NONE, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x014 */
    { FZC_COM_RX_TCU_HEARTBEAT,     4u,  1500u, TRUE ,  0u, 14u, COM_DEM_EVENT_NONE, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x015 */
    { FZC_COM_RX_BCM_HEARTBEAT,     4u,  1500u, TRUE ,  0u, 14u, COM_DEM_EVENT_NONE, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x016 */
    { FZC_COM_RX_VEHICLE_STATE,     6u,    30u, TRUE ,  5u,  3u, 12, 3u, 10u, COM_RTE_SIGNAL_NONE },   /* CAN 0x100 @satisfies SG-001,SG-008 */
    { FZC_COM_RX_TORQUE_REQUEST,     8u,    30u, TRUE ,  6u,  3u, COM_DEM_EVENT_NONE, 3u, 10u, COM_RTE_SIGNAL_NONE },   /* CAN 0x101 @satisfies SG-001 */
    { FZC_COM_RX_STEER_COMMAND,     8u,    30u, TRUE ,  7u,  3u, COM_DEM_EVENT_NONE, 3u, 10u, COM_RTE_SIGNAL_NONE },   /* CAN 0x102 @satisfies SG-003 */
    { FZC_COM_RX_BRAKE_COMMAND,     8u,    30u, TRUE ,  8u,  3u, COM_DEM_EVENT_NONE, 3u, 10u, COM_RTE_SIGNAL_NONE },   /* CAN 0x103 @satisfies SG-004 */
    { FZC_COM_RX_MOTOR_STATUS,     8u,   300u, TRUE , 14u, 12u, COM_DEM_EVENT_NONE, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x300 @satisfies SG-002,SG-006 */
    { FZC_COM_RX_MOTOR_CURRENT,     8u,   300u, TRUE , 15u, 12u, COM_DEM_EVENT_NONE, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x301 @satisfies SG-006 */
    { FZC_COM_RX_MOTOR_TEMPERATURE,     8u,   300u, TRUE ,  0u, 12u, COM_DEM_EVENT_NONE, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x302 @satisfies SG-006 */
    { FZC_COM_RX_BATTERY_STATUS,     6u,  3000u, TRUE ,  0u, 14u, COM_DEM_EVENT_NONE, 3u, 3u, COM_RTE_SIGNAL_NONE },   /* CAN 0x303 */
    { FZC_COM_RX_BODY_CONTROL_CMD,     4u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x350 */
    { FZC_COM_RX_LIGHT_STATUS,     4u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x400 */
    { FZC_COM_RX_INDICATOR_STATE,     4u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x401 */
    { FZC_COM_RX_DOOR_LOCK_STATUS,     2u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x402 */
    { FZC_COM_RX_DTC_BROADCAST,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x500 */
    { FZC_COM_RX_XCP_REQ_CVC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x550 */
    { FZC_COM_RX_XCP_RESP_CVC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x551 */
    { FZC_COM_RX_XCP_REQ_FZC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x552 */
    { FZC_COM_RX_XCP_REQ_RZC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x554 */
    { FZC_COM_RX_XCP_RESP_RZC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x555 */
    { FZC_COM_RX_XCP_REQ_SC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x556 */
    { FZC_COM_RX_XCP_RESP_SC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x557 */
    { FZC_COM_RX_FZC_VIRTUAL_SENSORS,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x600 */
    { FZC_COM_RX_RZC_VIRTUAL_SENSORS,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x601 */
    { FZC_COM_RX_UDS_RESP_TCU,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x644 */
    { FZC_COM_RX_UDS_FUNC_REQUEST,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x7DF */
    { FZC_COM_RX_UDS_PHYS_REQ_CVC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x7E0 */
    { FZC_COM_RX_UDS_PHYS_REQ_FZC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x7E1 */
    { FZC_COM_RX_UDS_PHYS_REQ_RZC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x7E2 */
    { FZC_COM_RX_UDS_PHYS_REQ_TCU,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x7E3 */
    { FZC_COM_RX_UDS_RESP_CVC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x7E8 */
    { FZC_COM_RX_UDS_RESP_RZC,     8u,     0u, FALSE,  0u,  2u, COM_DEM_EVENT_NONE, 0u, 0u, COM_RTE_SIGNAL_NONE },   /* CAN 0x7EA */
};

#define FZC_COM_RX_PDU_COUNT  (sizeof(fzc_rx_pdu_config) / sizeof(fzc_rx_pdu_config[0]))

/* ==================================================================
 * Aggregate Com Configuration
 * ================================================================== */

const Com_ConfigType fzc_com_config = {
    .signalConfig    = fzc_signal_config,
    .signalCount     = (uint8)FZC_COM_SIGNAL_COUNT,
    .txSignalConfig  = fzc_tx_signal_config,
    .txSignalCount   = FZC_COM_TX_SIGNAL_COUNT,
    .rxSignalConfig  = fzc_rx_signal_config,
    .rxSignalCount   = FZC_COM_RX_SIGNAL_COUNT,
    .txPduConfig     = fzc_tx_pdu_config,
    .txPduCount      = (uint8)FZC_COM_TX_PDU_COUNT,
    .rxPduConfig     = fzc_rx_pdu_config,
    .rxPduCount      = (uint8)FZC_COM_RX_PDU_COUNT,
    .mainFunctionPeriodMs = 10u,
};
