/**
 * @file    Os_Cfg_Fzc.h
 * @brief   OSEK kernel configuration for FZC — task/schedule-table/stack tables (S-OS-11)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef OS_CFG_FZC_H
#define OS_CFG_FZC_H

#include "Os.h"
#include "Os_Cfg_Types.h"

/* ==================================================================
 * Task IDs — one basic task per period group + mandatory idle task
 * (kernel convention, FMEA OS-C-03)
 * ================================================================== */

#define OS_TASK_FZC_10MS              ((TaskType)0u)
#define OS_TASK_FZC_50MS              ((TaskType)1u)
#define OS_TASK_FZC_100MS             ((TaskType)2u)
#define OS_TASK_FZC_5000MS            ((TaskType)3u)
#define OS_TASK_FZC_IDLE              ((TaskType)4u)
#define OS_TASK_COUNT_FZC             ((uint8)5u)

/* ==================================================================
 * Task priorities — shorter period = higher priority; numeric 0 is the
 * HIGHEST priority (Os_Scheduler.c os_select_next_ready_task scans
 * priority 0 upward). Idle sits at OS_MAX_PRIORITIES-1.
 * ================================================================== */

#define OS_TASK_PRIO_FZC_10MS             ((uint8)0u)
#define OS_TASK_PRIO_FZC_50MS             ((uint8)1u)
#define OS_TASK_PRIO_FZC_100MS            ((uint8)2u)
#define OS_TASK_PRIO_FZC_5000MS           ((uint8)3u)

/* ==================================================================
 * Schedule table IDs — one repeating table per period group
 * ================================================================== */

#define OS_TABLE_FZC_10MS             ((ScheduleTableType)0u)
#define OS_TABLE_FZC_50MS             ((ScheduleTableType)1u)
#define OS_TABLE_FZC_100MS            ((ScheduleTableType)2u)
#define OS_TABLE_FZC_5000MS           ((ScheduleTableType)3u)
#define OS_SCHED_TABLE_COUNT_FZC  ((uint8)4u)

/* ==================================================================
 * System counter — 1 tick per legacy RTE dispatch tick.
 * The kernel derives its counter base (AlarmBaseType) from alarm table
 * element 0 when alarms are configured; this configuration uses no
 * alarms, so the kernel default applies. The values below document that
 * base for integrators (must match Os_Core.c defaults).
 * ================================================================== */

#define FZC_OS_COUNTER_MAXALLOWEDVALUE  0xFFFFFFFFu
#define FZC_OS_COUNTER_TICKSPERBASE     1u
#define FZC_OS_COUNTER_MINCYCLE         1u

/* ==================================================================
 * Generated task bodies (Rte_TaskBodies_Fzc.c)
 * ================================================================== */

void Os_Task_Fzc_10ms(void);
void Os_Task_Fzc_50ms(void);
void Os_Task_Fzc_100ms(void);
void Os_Task_Fzc_5000ms(void);
void Os_Task_Fzc_Idle(void);

/* Aggregate kernel configuration — pass to Os_Configure() before StartOS */
extern const Os_ConfigType fzc_os_config;

/**
 * @brief   Start all period-group schedule tables (absolute start 0).
 * @return  E_OK, or the last non-OK status from StartScheduleTableAbs.
 * @note    Call once from a task context after StartOS (scheduler-cutover
 *          wiring): StartScheduleTableAbs is rejected outside TASK/ISR2
 *          call level by the SC3 service protection.
 */
StatusType Fzc_Os_StartScheduleTables(void);

#endif /* OS_CFG_FZC_H */
