/**
 * @file    Os_Cfg_Fzc.c
 * @brief   OSEK kernel configuration for FZC — task/schedule-table/stack tables (S-OS-11)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Os_Cfg_Fzc.h"

/* ==================================================================
 * S-OS-11 design notes
 *
 * Expiry-point offset rule: each period group gets ONE repeating
 * schedule table with Duration == period and a single expiry point at
 * offset == period, started at absolute tick 0. The group task is
 * therefore activated exactly at the counter ticks where the legacy
 * dispatcher (Rte_DispatchRunnables) fired the group's runnables
 * (tick % period == 0). Offsets are deliberately NOT staggered across
 * groups: staggering would shift activation phase and break the
 * S-OS-11 order-equivalence proof. Same-tick pileup is resolved by
 * task priority (shorter period = higher priority = runs first); the
 * generator refuses any ECU where that resolution would change the
 * legacy execution order.
 *
 * WdgM note: this file carries only kernel tables. The task BODIES —
 * including runnable dispatch order and WdgM_CheckpointReached calls
 * replicated from Rte_DispatchRunnables — are generated separately in
 * Rte_TaskBodies_Fzc.c.
 * ================================================================== */

/* ==================================================================
 * Task table — one basic task per period group + idle
 * Idle-task convention (kernel os_cfg_validate_idle_task, FMEA
 * OS-C-03): priority OS_MAX_PRIORITIES-1, autostarted in
 * OSDEFAULTAPPMODE, FULL. Its body never terminates (Assumption of Use).
 * ================================================================== */

static const Os_TaskConfigType fzc_os_task_cfg[OS_TASK_COUNT_FZC] = {
    /* Name, Entry, Priority, ActivationLimit, AutostartMask, Extended, Schedule */
    { "Fzc_10ms", Os_Task_Fzc_10ms, OS_TASK_PRIO_FZC_10MS, 1u, 0u, FALSE, FULL },
    { "Fzc_50ms", Os_Task_Fzc_50ms, OS_TASK_PRIO_FZC_50MS, 1u, 0u, FALSE, FULL },
    { "Fzc_100ms", Os_Task_Fzc_100ms, OS_TASK_PRIO_FZC_100MS, 1u, 0u, FALSE, FULL },
    { "Fzc_5000ms", Os_Task_Fzc_5000ms, OS_TASK_PRIO_FZC_5000MS, 1u, 0u, FALSE, FULL },
    { "Fzc_Idle", Os_Task_Fzc_Idle, (uint8)(OS_MAX_PRIORITIES - 1u), 1u, 1u, FALSE, FULL },
};

/* ==================================================================
 * Schedule tables — one repeating table per period group
 * ================================================================== */

static const Os_ExpiryPointConfigType fzc_os_ep_10ms[1] = {
    /* Offset, TaskID, EventMask */
    { 10u, OS_TASK_FZC_10MS, 0u },
};
static const Os_ExpiryPointConfigType fzc_os_ep_50ms[1] = {
    /* Offset, TaskID, EventMask */
    { 50u, OS_TASK_FZC_50MS, 0u },
};
static const Os_ExpiryPointConfigType fzc_os_ep_100ms[1] = {
    /* Offset, TaskID, EventMask */
    { 100u, OS_TASK_FZC_100MS, 0u },
};
static const Os_ExpiryPointConfigType fzc_os_ep_5000ms[1] = {
    /* Offset, TaskID, EventMask */
    { 5000u, OS_TASK_FZC_5000MS, 0u },
};

static const Os_ScheduleTableConfigType fzc_os_sched_table_cfg[OS_SCHED_TABLE_COUNT_FZC] = {
    /* Name, Duration, Repeating, ExpiryPoints, ExpiryPointCount */
    { "Fzc_10ms", 10u, TRUE, fzc_os_ep_10ms, 1u },
    { "Fzc_50ms", 50u, TRUE, fzc_os_ep_50ms, 1u },
    { "Fzc_100ms", 100u, TRUE, fzc_os_ep_100ms, 1u },
    { "Fzc_5000ms", 5000u, TRUE, fzc_os_ep_5000ms, 1u },
};

/* ==================================================================
 * Stack budgets (Os_StackMonitorConfigType) — from sidecar os: section
 * ================================================================== */

static const Os_StackMonitorConfigType fzc_os_stack_cfg[OS_TASK_COUNT_FZC] = {
    /* TaskID, BudgetBytes */
    { OS_TASK_FZC_10MS, 1024u },
    { OS_TASK_FZC_50MS, 1024u },
    { OS_TASK_FZC_100MS, 1024u },
    { OS_TASK_FZC_5000MS, 1024u },
    { OS_TASK_FZC_IDLE, 1024u },
};

/* ==================================================================
 * Aggregate kernel configuration
 * ================================================================== */

const Os_ConfigType fzc_os_config = {
    .Tasks = fzc_os_task_cfg,
    .TaskCount = OS_TASK_COUNT_FZC,
    .Resources = NULL_PTR,
    .ResourceCount = 0u,
    .Alarms = NULL_PTR,
    .AlarmCount = 0u,
    .ScheduleTables = fzc_os_sched_table_cfg,
    .ScheduleTableCount = OS_SCHED_TABLE_COUNT_FZC,
    .Applications = NULL_PTR,
    .ApplicationCount = 0u,
    .TrustedFunctions = NULL_PTR,
    .TrustedFunctionCount = 0u,
    .Iocs = NULL_PTR,
    .IocCount = 0u,
    .Stacks = fzc_os_stack_cfg,
    .StackCount = OS_TASK_COUNT_FZC,
    .MemoryRegions = NULL_PTR,
    .MemoryRegionCount = 0u,
    .MemProtTasks = NULL_PTR,
    .MemProtTaskCount = 0u,
};

/**
 * @brief   Start all period-group schedule tables at absolute tick 0
 * @return  E_OK, or the last non-OK status from StartScheduleTableAbs
 * @note    Task context only (SC3 service protection). The kernel
 *          processes expiry points from the NEXT counter tick, so an
 *          absolute start of 0 fires each table first at tick == period
 *          — the legacy dispatcher's phase.
 */
StatusType Fzc_Os_StartScheduleTables(void)
{
    StatusType status = E_OK;
    uint8 idx;

    for (idx = 0u; idx < OS_SCHED_TABLE_COUNT_FZC; idx++) {
        StatusType table_status = StartScheduleTableAbs((ScheduleTableType)idx, 0u);
        if (table_status != E_OK) {
            status = table_status;
        }
    }

    return status;
}
