/**
 * @file    Rte_Cfg_Fzc.c
 * @brief   RTE configuration for FZC — signal table and runnable table
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Rte.h"
#include "Fzc_Cfg.h"

/* ==================================================================
 * Forward declarations for SWC runnables
 * ================================================================== */

extern void Swc_Brake_MainFunction(void);
extern void Swc_Brake_Init(void);
extern void Can_MainFunction_Read(void);
extern void Com_MainFunction_Rx(void);
extern void Com_MainFunction_Tx(void);
extern void Can_MainFunction_BusOff(void);
extern void Swc_Buzzer_MainFunction(void);
extern void Swc_Buzzer_Init(void);
extern void Swc_FzcCanMonitor_Check(void);
extern void Swc_FzcCanMonitor_Init(void);
extern void Swc_FzcCom_Init(void);
extern void Swc_FzcCom_Receive(void);  /* TODO:CODEGEN wire via sidecar */
extern void Swc_FzcDcm_Init(void);
extern void Swc_FzcNvm_Init(void);
extern void Swc_FzcSafety_MainFunction(void);
extern void Swc_FzcSafety_Init(void);
extern void Swc_FzcScheduler_Init(void);
extern void Swc_FzcSensorFeeder_MainFunction(void);
extern void Swc_FzcSensorFeeder_Init(void);
extern void Swc_Heartbeat_MainFunction(void);
extern void Swc_Lidar_MainFunction(void);
extern void Swc_Lidar_Init(void);
extern void Swc_Steering_MainFunction(void);
extern void Swc_Steering_Init(void);

/* ==================================================================
 * Signal Configuration Table
 * ================================================================== */

static const Rte_SignalConfigType fzc_signal_config[FZC_SIG_COUNT] = {
    /* BSW well-known signals (0-15) — initial values */
    {  0u, 0u },   /* RTE_SIG_TORQUE_REQUEST */
    {  1u, 0u },   /* RTE_SIG_STEERING_ANGLE */
    {  2u, 0u },   /* RTE_SIG_VEHICLE_SPEED */
    {  3u, 0u },   /* RTE_SIG_BRAKE_PRESSURE */
    {  4u, 0u },   /* RTE_SIG_MOTOR_STATUS */
    {  5u, 0u },   /* RTE_SIG_BATTERY_VOLTAGE */
    {  6u, 0u },   /* RTE_SIG_BATTERY_CURRENT */
    {  7u, 0u },   /* RTE_SIG_MOTOR_TEMP */
    {  8u, 0u },   /* RTE_SIG_ESTOP_STATUS */
    {  9u, 0u },   /* RTE_SIG_HEARTBEAT */
    { 10u, 0u },   /* Reserved                */
    { 11u, 0u },   /* Reserved                */
    { 12u, 0u },   /* Reserved                */
    { 13u, 0u },   /* Reserved                */
    { 14u, 0u },   /* Reserved                */
    { 15u, 0u },   /* Reserved                */

    /* FZC application signals (16+) */
    { FZC_SIG_BCM_HEARTBEAT_ALIVE_COUNTER, 0u },   /* 16: BCM_Heartbeat_AliveCounter */
    { FZC_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 17: BCM_Heartbeat_E2E_AliveCounter */
    { FZC_SIG_BCM_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 18: BCM_Heartbeat_E2E_CRC8 */
    { FZC_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 19: BCM_Heartbeat_E2E_DataID */
    { FZC_SIG_BCM_HEARTBEAT_ECU_ID, 0u },   /* 20: BCM_Heartbeat_ECU_ID */
    { FZC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V, 0u },   /* 21: Battery_Status_BatteryVoltage_mV */
    { FZC_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 22: Battery_Status_E2E_AliveCounter */
    { FZC_SIG_BATTERY_STATUS_E_2_E_CRC_8, 0u },   /* 23: Battery_Status_E2E_CRC8 */
    { FZC_SIG_BATTERY_STATUS_E_2_E_DATA_ID, 0u },   /* 24: Battery_Status_E2E_DataID */
    { FZC_SIG_BATTERY_STATUS_LEVEL, 0u },   /* 25: Battery_Status_Level */
    { FZC_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD, 0u },   /* 26: Body_Control_Cmd_DoorLockCmd */
    { FZC_SIG_BODY_CONTROL_CMD_HAZARD_ACTIVE, 0u },   /* 27: Body_Control_Cmd_HazardActive */
    { FZC_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD, 0u },   /* 28: Body_Control_Cmd_HeadlightCmd */
    { FZC_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_ON, 0u },   /* 29: Body_Control_Cmd_TailLightOn */
    { FZC_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD, 0u },   /* 30: Body_Control_Cmd_TurnSignalCmd */
    { FZC_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD, 0u },   /* 31: Brake_Command_BrakeForceCmd */
    { FZC_SIG_BRAKE_COMMAND_BRAKE_MODE, 0u },   /* 32: Brake_Command_BrakeMode */
    { FZC_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER, 0u },   /* 33: Brake_Command_E2E_AliveCounter */
    { FZC_SIG_BRAKE_COMMAND_E_2_E_CRC_8, 0u },   /* 34: Brake_Command_E2E_CRC8 */
    { FZC_SIG_BRAKE_COMMAND_E_2_E_DATA_ID, 0u },   /* 35: Brake_Command_E2E_DataID */
    { FZC_SIG_BRAKE_COMMAND_VEHICLE_STATE, 0u },   /* 36: Brake_Command_VehicleState */
    { FZC_SIG_BRAKE_FAULT_COMMANDED_BRAKE, 0u },   /* 37: Brake_Fault_CommandedBrake */
    { FZC_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER, 0u },   /* 38: Brake_Fault_E2E_AliveCounter */
    { FZC_SIG_BRAKE_FAULT_E_2_E_CRC_8, 0u },   /* 39: Brake_Fault_E2E_CRC8 */
    { FZC_SIG_BRAKE_FAULT_E_2_E_DATA_ID, 0u },   /* 40: Brake_Fault_E2E_DataID */
    { FZC_SIG_BRAKE_FAULT_FAULT_TYPE, 0u },   /* 41: Brake_Fault_FaultType */
    { FZC_SIG_BRAKE_FAULT_MEASURED_BRAKE, 0u },   /* 42: Brake_Fault_MeasuredBrake */
    { FZC_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO, 0u },   /* 43: Brake_Status_BrakeCommandEcho */
    { FZC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS, 0u },   /* 44: Brake_Status_BrakeFaultStatus */
    { FZC_SIG_BRAKE_STATUS_BRAKE_MODE, 0u },   /* 45: Brake_Status_BrakeMode */
    { FZC_SIG_BRAKE_STATUS_BRAKE_POSITION, 0u },   /* 46: Brake_Status_BrakePosition */
    { FZC_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 47: Brake_Status_E2E_AliveCounter */
    { FZC_SIG_BRAKE_STATUS_E_2_E_CRC_8, 0u },   /* 48: Brake_Status_E2E_CRC8 */
    { FZC_SIG_BRAKE_STATUS_E_2_E_DATA_ID, 0u },   /* 49: Brake_Status_E2E_DataID */
    { FZC_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A, 0u },   /* 50: Brake_Status_ServoCurrent_mA */
    { FZC_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 51: CVC_Heartbeat_E2E_AliveCounter */
    { FZC_SIG_CVC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 52: CVC_Heartbeat_E2E_CRC8 */
    { FZC_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 53: CVC_Heartbeat_E2E_DataID */
    { FZC_SIG_CVC_HEARTBEAT_ECU_ID, 0u },   /* 54: CVC_Heartbeat_ECU_ID */
    { FZC_SIG_CVC_HEARTBEAT_FAULT_STATUS, 0u },   /* 55: CVC_Heartbeat_FaultStatus */
    { FZC_SIG_CVC_HEARTBEAT_OPERATING_MODE, 0u },   /* 56: CVC_Heartbeat_OperatingMode */
    { FZC_SIG_DTC_BROADCAST_ECU_SOURCE, 0u },   /* 57: DTC_Broadcast_ECU_Source */
    { FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_0, 0u },   /* 58: DTC_Broadcast_FreezeFrame0 */
    { FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_1, 0u },   /* 59: DTC_Broadcast_FreezeFrame1 */
    { FZC_SIG_DTC_BROADCAST_NUMBER, 0u },   /* 60: DTC_Broadcast_Number */
    { FZC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT, 0u },   /* 61: DTC_Broadcast_OccurrenceCount */
    { FZC_SIG_DTC_BROADCAST_STATUS, 0u },   /* 62: DTC_Broadcast_Status */
    { FZC_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK, 0u },   /* 63: Door_Lock_Status_CentralLock */
    { FZC_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK, 0u },   /* 64: Door_Lock_Status_FrontLeftLock */
    { FZC_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK, 0u },   /* 65: Door_Lock_Status_FrontRightLock */
    { FZC_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK, 0u },   /* 66: Door_Lock_Status_RearLeftLock */
    { FZC_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK, 0u },   /* 67: Door_Lock_Status_RearRightLock */
    { FZC_SIG_ESTOP_BROADCAST_ACTIVE, 0u },   /* 68: EStop_Broadcast_Active */
    { FZC_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER, 0u },   /* 69: EStop_Broadcast_E2E_AliveCounter */
    { FZC_SIG_ESTOP_BROADCAST_E_2_E_CRC_8, 0u },   /* 70: EStop_Broadcast_E2E_CRC8 */
    { FZC_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID, 0u },   /* 71: EStop_Broadcast_E2E_DataID */
    { FZC_SIG_ESTOP_BROADCAST_SOURCE, 0u },   /* 72: EStop_Broadcast_Source */
    { FZC_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 73: FZC_Heartbeat_E2E_AliveCounter */
    { FZC_SIG_FZC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 74: FZC_Heartbeat_E2E_CRC8 */
    { FZC_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 75: FZC_Heartbeat_E2E_DataID */
    { FZC_SIG_FZC_HEARTBEAT_ECU_ID, 0u },   /* 76: FZC_Heartbeat_ECU_ID */
    { FZC_SIG_FZC_HEARTBEAT_FAULT_STATUS, 0u },   /* 77: FZC_Heartbeat_FaultStatus */
    { FZC_SIG_FZC_HEARTBEAT_OPERATING_MODE, 0u },   /* 78: FZC_Heartbeat_OperatingMode */
    { FZC_SIG_FZC_VIRTUAL_SENSORS_BRAKE_CURRENT_M_A, 0u },   /* 79: FZC_Virtual_Sensors_BrakeCurrent_mA */
    { FZC_SIG_FZC_VIRTUAL_SENSORS_BRAKE_POS_ADC, 0u },   /* 80: FZC_Virtual_Sensors_BrakePos_ADC */
    { FZC_SIG_FZC_VIRTUAL_SENSORS_STEER_ANGLE_RAW, 0u },   /* 81: FZC_Virtual_Sensors_SteerAngle_Raw */
    { FZC_SIG_ICU_HEARTBEAT_ALIVE_COUNTER, 0u },   /* 82: ICU_Heartbeat_AliveCounter */
    { FZC_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 83: ICU_Heartbeat_E2E_AliveCounter */
    { FZC_SIG_ICU_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 84: ICU_Heartbeat_E2E_CRC8 */
    { FZC_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 85: ICU_Heartbeat_E2E_DataID */
    { FZC_SIG_ICU_HEARTBEAT_ECU_ID, 0u },   /* 86: ICU_Heartbeat_ECU_ID */
    { FZC_SIG_INDICATOR_STATE_BLINK_PHASE_HIGH, 0u },   /* 87: Indicator_State_BlinkPhaseHigh */
    { FZC_SIG_INDICATOR_STATE_HAZARD_ACTIVE, 0u },   /* 88: Indicator_State_HazardActive */
    { FZC_SIG_INDICATOR_STATE_LEFT_ON, 0u },   /* 89: Indicator_State_LeftOn */
    { FZC_SIG_INDICATOR_STATE_RIGHT_ON, 0u },   /* 90: Indicator_State_RightOn */
    { FZC_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER, 0u },   /* 91: Lidar_Distance_E2E_AliveCounter */
    { FZC_SIG_LIDAR_DISTANCE_E_2_E_CRC_8, 0u },   /* 92: Lidar_Distance_E2E_CRC8 */
    { FZC_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID, 0u },   /* 93: Lidar_Distance_E2E_DataID */
    { FZC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE, 0u },   /* 94: Lidar_Distance_ObstacleZone */
    { FZC_SIG_LIDAR_DISTANCE_RANGE_CM, 0u },   /* 95: Lidar_Distance_Range_cm */
    { FZC_SIG_LIDAR_DISTANCE_SENSOR_STATUS, 0u },   /* 96: Lidar_Distance_SensorStatus */
    { FZC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH, 0u },   /* 97: Lidar_Distance_SignalStrength */
    { FZC_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON, 0u },   /* 98: Light_Status_BrakeLightOn */
    { FZC_SIG_LIGHT_STATUS_FOG_LIGHT_ON, 0u },   /* 99: Light_Status_FogLightOn */
    { FZC_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL, 0u },   /* 100: Light_Status_HeadlightLevel */
    { FZC_SIG_LIGHT_STATUS_HEADLIGHT_ON, 0u },   /* 101: Light_Status_HeadlightOn */
    { FZC_SIG_LIGHT_STATUS_TAIL_LIGHT_ON, 0u },   /* 102: Light_Status_TailLightOn */
    { FZC_SIG_MOTOR_CURRENT_DIR_IS_REVERSE, 0u },   /* 103: Motor_Current_DirIsReverse */
    { FZC_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER, 0u },   /* 104: Motor_Current_E2E_AliveCounter */
    { FZC_SIG_MOTOR_CURRENT_E_2_E_CRC_8, 0u },   /* 105: Motor_Current_E2E_CRC8 */
    { FZC_SIG_MOTOR_CURRENT_E_2_E_DATA_ID, 0u },   /* 106: Motor_Current_E2E_DataID */
    { FZC_SIG_MOTOR_CURRENT_MOTOR_ENABLE, 0u },   /* 107: Motor_Current_MotorEnable */
    { FZC_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG, 0u },   /* 108: Motor_Current_OvercurrentFlag */
    { FZC_SIG_MOTOR_CURRENT_PHASE_M_A, 0u },   /* 109: Motor_Current_Phase_mA */
    { FZC_SIG_MOTOR_CURRENT_TORQUE_ECHO, 0u },   /* 110: Motor_Current_TorqueEcho */
    { FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER, 0u },   /* 111: Motor_Cutoff_Req_E2E_AliveCounter */
    { FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8, 0u },   /* 112: Motor_Cutoff_Req_E2E_CRC8 */
    { FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID, 0u },   /* 113: Motor_Cutoff_Req_E2E_DataID */
    { FZC_SIG_MOTOR_CUTOFF_REQ_REASON, 0u },   /* 114: Motor_Cutoff_Req_Reason */
    { FZC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE, 0u },   /* 115: Motor_Cutoff_Req_RequestType */
    { FZC_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 116: Motor_Status_E2E_AliveCounter */
    { FZC_SIG_MOTOR_STATUS_E_2_E_CRC_8, 0u },   /* 117: Motor_Status_E2E_CRC8 */
    { FZC_SIG_MOTOR_STATUS_E_2_E_DATA_ID, 0u },   /* 118: Motor_Status_E2E_DataID */
    { FZC_SIG_MOTOR_STATUS_MOTOR_DIRECTION, 0u },   /* 119: Motor_Status_MotorDirection */
    { FZC_SIG_MOTOR_STATUS_MOTOR_ENABLE, 0u },   /* 120: Motor_Status_MotorEnable */
    { FZC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS, 0u },   /* 121: Motor_Status_MotorFaultStatus */
    { FZC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM, 0u },   /* 122: Motor_Status_MotorSpeed_RPM */
    { FZC_SIG_MOTOR_STATUS_TORQUE_ECHO, 0u },   /* 123: Motor_Status_TorqueEcho */
    { FZC_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT, 0u },   /* 124: Motor_Temperature_DeratingPercent */
    { FZC_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER, 0u },   /* 125: Motor_Temperature_E2E_AliveCounter */
    { FZC_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8, 0u },   /* 126: Motor_Temperature_E2E_CRC8 */
    { FZC_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID, 0u },   /* 127: Motor_Temperature_E2E_DataID */
    { FZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C, 0u },   /* 128: Motor_Temperature_WindingTemp1_C */
    { FZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C, 0u },   /* 129: Motor_Temperature_WindingTemp2_C */
    { FZC_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 130: RZC_Heartbeat_E2E_AliveCounter */
    { FZC_SIG_RZC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 131: RZC_Heartbeat_E2E_CRC8 */
    { FZC_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 132: RZC_Heartbeat_E2E_DataID */
    { FZC_SIG_RZC_HEARTBEAT_ECU_ID, 0u },   /* 133: RZC_Heartbeat_ECU_ID */
    { FZC_SIG_RZC_HEARTBEAT_FAULT_STATUS, 0u },   /* 134: RZC_Heartbeat_FaultStatus */
    { FZC_SIG_RZC_HEARTBEAT_OPERATING_MODE, 0u },   /* 135: RZC_Heartbeat_OperatingMode */
    { FZC_SIG_RZC_VIRTUAL_SENSORS_BATT_VOLTAGE_M_V, 0u },   /* 136: RZC_Virtual_Sensors_BattVoltage_mV */
    { FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_CURRENT_M_A, 0u },   /* 137: RZC_Virtual_Sensors_MotorCurrent_mA */
    { FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_SPEED_RPM, 0u },   /* 138: RZC_Virtual_Sensors_MotorSpeed_RPM */
    { FZC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_TEMP_D_C, 0u },   /* 139: RZC_Virtual_Sensors_MotorTemp_dC */
    { FZC_SIG_SC_STATUS_ALIVE_COUNTER, 0u },   /* 140: SC_Status_AliveCounter */
    { FZC_SIG_SC_STATUS_CRC_8, 0u },   /* 141: SC_Status_CRC8 */
    { FZC_SIG_SC_STATUS_ECU_HEALTH, 0u },   /* 142: SC_Status_ECU_Health */
    { FZC_SIG_SC_STATUS_FAULT_FLAGS, 0u },   /* 143: SC_Status_FaultFlags */
    { FZC_SIG_SC_STATUS_FAULT_REASON, 0u },   /* 144: SC_Status_FaultReason */
    { FZC_SIG_SC_STATUS_MODE, 0u },   /* 145: SC_Status_Mode */
    { FZC_SIG_SC_STATUS_RELAY_ENERGIZED, 0u },   /* 146: SC_Status_RelayEnergized */
    { FZC_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER, 0u },   /* 147: Steer_Command_E2E_AliveCounter */
    { FZC_SIG_STEER_COMMAND_E_2_E_CRC_8, 0u },   /* 148: Steer_Command_E2E_CRC8 */
    { FZC_SIG_STEER_COMMAND_E_2_E_DATA_ID, 0u },   /* 149: Steer_Command_E2E_DataID */
    { FZC_SIG_STEER_COMMAND_STEER_ANGLE_CMD, 0u },   /* 150: Steer_Command_SteerAngleCmd */
    { FZC_SIG_STEER_COMMAND_STEER_RATE_LIMIT, 0u },   /* 151: Steer_Command_SteerRateLimit */
    { FZC_SIG_STEER_COMMAND_VEHICLE_STATE, 0u },   /* 152: Steer_Command_VehicleState */
    { FZC_SIG_STEERING_STATUS_ACTUAL_ANGLE, 0u },   /* 153: Steering_Status_ActualAngle */
    { FZC_SIG_STEERING_STATUS_COMMANDED_ANGLE, 0u },   /* 154: Steering_Status_CommandedAngle */
    { FZC_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 155: Steering_Status_E2E_AliveCounter */
    { FZC_SIG_STEERING_STATUS_E_2_E_CRC_8, 0u },   /* 156: Steering_Status_E2E_CRC8 */
    { FZC_SIG_STEERING_STATUS_E_2_E_DATA_ID, 0u },   /* 157: Steering_Status_E2E_DataID */
    { FZC_SIG_STEERING_STATUS_SERVO_CURRENT_M_A, 0u },   /* 158: Steering_Status_ServoCurrent_mA */
    { FZC_SIG_STEERING_STATUS_STEER_FAULT_STATUS, 0u },   /* 159: Steering_Status_SteerFaultStatus */
    { FZC_SIG_STEERING_STATUS_STEER_MODE, 0u },   /* 160: Steering_Status_SteerMode */
    { FZC_SIG_TCU_HEARTBEAT_ALIVE_COUNTER, 0u },   /* 161: TCU_Heartbeat_AliveCounter */
    { FZC_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 162: TCU_Heartbeat_E2E_AliveCounter */
    { FZC_SIG_TCU_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 163: TCU_Heartbeat_E2E_CRC8 */
    { FZC_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 164: TCU_Heartbeat_E2E_DataID */
    { FZC_SIG_TCU_HEARTBEAT_ECU_ID, 0u },   /* 165: TCU_Heartbeat_ECU_ID */
    { FZC_SIG_TORQUE_REQUEST_COMMAND_PCT, 0u },   /* 166: Torque_Request_Command_pct */
    { FZC_SIG_TORQUE_REQUEST_DIRECTION, 0u },   /* 167: Torque_Request_Direction */
    { FZC_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER, 0u },   /* 168: Torque_Request_E2E_AliveCounter */
    { FZC_SIG_TORQUE_REQUEST_E_2_E_CRC_8, 0u },   /* 169: Torque_Request_E2E_CRC8 */
    { FZC_SIG_TORQUE_REQUEST_E_2_E_DATA_ID, 0u },   /* 170: Torque_Request_E2E_DataID */
    { FZC_SIG_TORQUE_REQUEST_PEDAL_FAULT, 0u },   /* 171: Torque_Request_PedalFault */
    { FZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1, 0u },   /* 172: Torque_Request_PedalPosition1 */
    { FZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2, 0u },   /* 173: Torque_Request_PedalPosition2 */
    { FZC_SIG_UDS_FUNC_REQUEST_UDS_DATA, 0u },   /* 174: UDS_Func_Request_UDS_Data */
    { FZC_SIG_UDS_PHYS_REQ_CVC_UDS_DATA, 0u },   /* 175: UDS_Phys_Req_CVC_UDS_Data */
    { FZC_SIG_UDS_PHYS_REQ_FZC_UDS_DATA, 0u },   /* 176: UDS_Phys_Req_FZC_UDS_Data */
    { FZC_SIG_UDS_PHYS_REQ_RZC_UDS_DATA, 0u },   /* 177: UDS_Phys_Req_RZC_UDS_Data */
    { FZC_SIG_UDS_PHYS_REQ_TCU_UDS_DATA, 0u },   /* 178: UDS_Phys_Req_TCU_UDS_Data */
    { FZC_SIG_UDS_RESP_CVC_UDS_DATA, 0u },   /* 179: UDS_Resp_CVC_UDS_Data */
    { FZC_SIG_UDS_RESP_FZC_UDS_DATA, 0u },   /* 180: UDS_Resp_FZC_UDS_Data */
    { FZC_SIG_UDS_RESP_RZC_UDS_DATA, 0u },   /* 181: UDS_Resp_RZC_UDS_Data */
    { FZC_SIG_UDS_RESP_TCU_UDS_DATA, 0u },   /* 182: UDS_Resp_TCU_UDS_Data */
    { FZC_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER, 0u },   /* 183: Vehicle_State_E2E_AliveCounter */
    { FZC_SIG_VEHICLE_STATE_E_2_E_CRC_8, 0u },   /* 184: Vehicle_State_E2E_CRC8 */
    { FZC_SIG_VEHICLE_STATE_E_2_E_DATA_ID, 0u },   /* 185: Vehicle_State_E2E_DataID */
    { FZC_SIG_VEHICLE_STATE_FAULT_MASK, 0u },   /* 186: Vehicle_State_FaultMask */
    { FZC_SIG_VEHICLE_STATE_MODE, 0u },   /* 187: Vehicle_State_Mode */
    { FZC_SIG_VEHICLE_STATE_SPEED_LIMIT, 0u },   /* 188: Vehicle_State_SpeedLimit */
    { FZC_SIG_VEHICLE_STATE_TORQUE_LIMIT, 0u },   /* 189: Vehicle_State_TorqueLimit */
    { FZC_SIG_XCP_REQ_CVC_DATA, 0u },   /* 190: XCP_Req_CVC_Data */
    { FZC_SIG_XCP_REQ_FZC_DATA, 0u },   /* 191: XCP_Req_FZC_Data */
    { FZC_SIG_XCP_REQ_RZC_DATA, 0u },   /* 192: XCP_Req_RZC_Data */
    { FZC_SIG_XCP_REQ_SC_DATA, 0u },   /* 193: XCP_Req_SC_Data */
    { FZC_SIG_XCP_RESP_CVC_DATA, 0u },   /* 194: XCP_Resp_CVC_Data */
    { FZC_SIG_XCP_RESP_FZC_DATA, 0u },   /* 195: XCP_Resp_FZC_Data */
    { FZC_SIG_XCP_RESP_RZC_DATA, 0u },   /* 196: XCP_Resp_RZC_Data */
    { FZC_SIG_XCP_RESP_SC_DATA, 0u },   /* 197: XCP_Resp_SC_Data */
};

/* ==================================================================
 * Runnable Configuration Table
 * Priority: higher number = executes first within same period
 * ================================================================== */

static const Rte_RunnableConfigType fzc_runnable_config[] = {
    /* func,                        periodMs, priority, seId */
    { Can_MainFunction_Read,                      10u,    14u, 0xFFu },
    { Com_MainFunction_Rx,                        10u,    13u, 0xFFu },
    { Swc_FzcCom_Receive,                         10u,    12u, 0xFFu },  /* TODO:CODEGEN resets CanMon silence counter; without this, FZC spuriously declares BUS_OFF and forces brake=100 */
    { Swc_FzcSensorFeeder_MainFunction,           10u,    11u, 0xFFu },
    { Swc_Steering_MainFunction,                  10u,    10u, 0x00u },
    { Swc_Brake_MainFunction,                     10u,     9u, 0x01u },
    { Swc_Lidar_MainFunction,                     10u,     8u, 0x02u },
    { Swc_Heartbeat_MainFunction,                 50u,     7u, 0x03u },
    { Swc_FzcSafety_MainFunction,                 10u,     6u, 0x04u },
    { Swc_Buzzer_MainFunction,                    10u,     5u, 0x05u },
    { Swc_FzcCanMonitor_Check,                    10u,     4u, 0xFFu },
    { Com_MainFunction_Tx,                        10u,     2u, 0xFFu },
    { Can_MainFunction_BusOff,                    10u,     1u, 0xFFu },
};

#define FZC_RUNNABLE_COUNT  (sizeof(fzc_runnable_config) / sizeof(fzc_runnable_config[0]))

/* ==================================================================
 * Aggregate RTE Configuration
 * ================================================================== */

const Rte_ConfigType fzc_rte_config = {
    .signalConfig   = fzc_signal_config,
    .signalCount    = FZC_SIG_COUNT,
    .runnableConfig = fzc_runnable_config,
    .runnableCount  = (uint8)FZC_RUNNABLE_COUNT,
};
