/**
 * @file    Rte_TaskBodies_Fzc.c
 * @brief   Generated OSEK task bodies for FZC — legacy-order runnable dispatch (S-OS-11)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Os_Cfg_Fzc.h"
#include "Os_TaskMap.h"
#include "WdgM.h"

/* ==================================================================
 * S-OS-11 task bodies — legacy-order runnable dispatch
 *
 * Each period-group task body calls its runnables in EXACTLY the order
 * the legacy dispatcher (Rte_DispatchRunnables, Rte.c:40-105) executed
 * them: priority descending, ties broken by runnable-table index. The
 * generator proves this order equivalence over an LCM-of-periods window
 * before emitting this file and refuses the ECU otherwise.
 *
 * WdgM checkpoints replicate Rte.c:93-100 (once per unique seId per
 * dispatch, seId < RTE_MAX_RUNNABLES): the once-per-seId bookkeeping is
 * resolved at generation time — the checkpoint call is emitted after
 * the FIRST runnable of each unique valid seId in the group.
 *
 * Os_TaskMap_RunMappedFunctions() bridges the super-loop BSW slot
 * MainFunctions into the same period task (empty no-op map until the
 * ECU main registers its table via Os_TaskMap_SetTable before StartOS).
 *
 * Basic-task pattern: every period task terminates via TerminateTask()
 * (schedule-table expiry points re-activate it each period).
 * ================================================================== */

/* Forward declarations for SWC/BSW runnables */
extern void Can_MainFunction_Read(void);
extern void Com_MainFunction_Rx(void);
extern void Swc_FzcCom_Receive(void);
extern void Swc_FzcSensorFeeder_MainFunction(void);
extern void Swc_Steering_MainFunction(void);
extern void Swc_Brake_MainFunction(void);
extern void Swc_Lidar_MainFunction(void);
extern void Swc_FzcSafety_MainFunction(void);
extern void Swc_Buzzer_MainFunction(void);
extern void Swc_FzcCanMonitor_Check(void);
extern void Com_MainFunction_Tx(void);
extern void Can_MainFunction_BusOff(void);
extern void Swc_Heartbeat_MainFunction(void);

/**
 * @brief   10 ms period-group task (12 runnables)
 * @note    Activated by schedule table OS_TABLE_FZC_10MS at every
 *          counter tick with tick % 10 == 0.
 */
void Os_Task_Fzc_10ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_FZC_10MS);

    Can_MainFunction_Read();
    Com_MainFunction_Rx();
    Swc_FzcCom_Receive();
    Swc_FzcSensorFeeder_MainFunction();
    Swc_Steering_MainFunction();
    (void)WdgM_CheckpointReached(0x00u);
    Swc_Brake_MainFunction();
    (void)WdgM_CheckpointReached(0x01u);
    Swc_Lidar_MainFunction();
    (void)WdgM_CheckpointReached(0x02u);
    Swc_FzcSafety_MainFunction();
    (void)WdgM_CheckpointReached(0x04u);
    Swc_Buzzer_MainFunction();
    (void)WdgM_CheckpointReached(0x05u);
    Swc_FzcCanMonitor_Check();
    Com_MainFunction_Tx();
    Can_MainFunction_BusOff();
    (void)TerminateTask();
}

/**
 * @brief   50 ms period-group task (1 runnable)
 * @note    Activated by schedule table OS_TABLE_FZC_50MS at every
 *          counter tick with tick % 50 == 0.
 */
void Os_Task_Fzc_50ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_FZC_50MS);

    Swc_Heartbeat_MainFunction();
    (void)WdgM_CheckpointReached(0x03u);
    (void)TerminateTask();
}

/**
 * @brief   100 ms period-group task (0 runnables)
 * @note    Activated by schedule table OS_TABLE_FZC_100MS at every
 *          counter tick with tick % 100 == 0.
 */
void Os_Task_Fzc_100ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_FZC_100MS);

    (void)TerminateTask();
}

/**
 * @brief   5000 ms period-group task (0 runnables)
 * @note    Activated by schedule table OS_TABLE_FZC_5000MS at every
 *          counter tick with tick % 5000 == 0.
 */
void Os_Task_Fzc_5000ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_FZC_5000MS);

    (void)TerminateTask();
}

/**
 * @brief   Idle task — lowest priority, autostarted, never terminates
 * @note    Assumption of Use (kernel os_cfg_validate_idle_task): the
 *          idle body must not return. As the autostarted task it is the
 *          scheduler-cutover bootstrap context: it starts the period
 *          schedule tables once (task call level, SC3 service
 *          protection), then loops on the idle task-map hook so the
 *          per-ECU map can bind the platform low-power idle action
 *          (e.g. Main_Hw_Wfi). With the weak-empty map the loop is the
 *          previous bare spin.
 */
void Os_Task_Fzc_Idle(void)
{
    (void)Fzc_Os_StartScheduleTables();

    for (;;) {
        Os_TaskMap_RunMappedFunctions(OS_TASK_FZC_IDLE);
    }
}
