/**
 * @file    Rte_Swc_FzcSafety.h
 * @brief   Typed RTE wrappers for Swc_FzcSafety (FZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_FZCSAFETY_H
#define RTE_SWC_FZCSAFETY_H

#include "Rte.h"
#include "Fzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_FzcSafety
 *
 * Usage: #include "Rte_Swc_FzcSafety.h" in Swc_FzcSafety source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Write Motor_Cutoff_Req_E2E_AliveCounter (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Motor_Cutoff_Req_E2E_AliveCounter(uint8_t value)
{
    return Rte_Write(FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER, (uint32_t)value);
}

/**
 * @brief  Write Motor_Cutoff_Req_E2E_CRC8 (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Motor_Cutoff_Req_E2E_CRC8(uint8_t value)
{
    return Rte_Write(FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8, (uint32_t)value);
}

/**
 * @brief  Write Motor_Cutoff_Req_E2E_DataID (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Motor_Cutoff_Req_E2E_DataID(uint8_t value)
{
    return Rte_Write(FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID, (uint32_t)value);
}

/**
 * @brief  Write Motor_Cutoff_Req_Reason (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Motor_Cutoff_Req_Reason(uint8_t value)
{
    return Rte_Write(FZC_SIG_MOTOR_CUTOFF_REQ_REASON, (uint32_t)value);
}

/**
 * @brief  Write Motor_Cutoff_Req_RequestType (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Motor_Cutoff_Req_RequestType(uint8_t value)
{
    return Rte_Write(FZC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE, (uint32_t)value);
}

#endif /* RTE_SWC_FZCSAFETY_H */
