/**
 * @file    Rte_PbCfg.h
 * @brief   RTE buffer limits for FZC — sizes static arrays in Rte.c
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_PBCFG_H
#define RTE_PBCFG_H

/**
 * @brief  Per-ECU RTE buffer limits — included by Rte.h via __has_include
 *
 * These values size the static signal buffer and runnable arrays in Rte.c.
 * They MUST be consistent across all translation units that include Rte.h.
 */
#define RTE_MAX_SIGNALS    205u
#define RTE_MAX_RUNNABLES  13u

#endif /* RTE_PBCFG_H */
