/**
 * @file    Rte_Swc_Lidar.h
 * @brief   Typed RTE wrappers for Swc_Lidar (FZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_LIDAR_H
#define RTE_SWC_LIDAR_H

#include "Rte.h"
#include "Fzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Lidar
 *
 * Usage: #include "Rte_Swc_Lidar.h" in Swc_Lidar source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Write Lidar_Distance_E2E_AliveCounter (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Lidar_Distance_E2E_AliveCounter(uint8_t value)
{
    return Rte_Write(FZC_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER, (uint32_t)value);
}

/**
 * @brief  Write Lidar_Distance_E2E_CRC8 (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Lidar_Distance_E2E_CRC8(uint8_t value)
{
    return Rte_Write(FZC_SIG_LIDAR_DISTANCE_E_2_E_CRC_8, (uint32_t)value);
}

/**
 * @brief  Write Lidar_Distance_E2E_DataID (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Lidar_Distance_E2E_DataID(uint8_t value)
{
    return Rte_Write(FZC_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID, (uint32_t)value);
}

/**
 * @brief  Write Lidar_Distance_ObstacleZone (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Lidar_Distance_ObstacleZone(uint8_t value)
{
    return Rte_Write(FZC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE, (uint32_t)value);
}

/**
 * @brief  Write Lidar_Distance_Range_cm (uint16_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Lidar_Distance_Range_cm(uint16_t value)
{
    return Rte_Write(FZC_SIG_LIDAR_DISTANCE_RANGE_CM, (uint32_t)value);
}

/**
 * @brief  Write Lidar_Distance_SensorStatus (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Lidar_Distance_SensorStatus(uint8_t value)
{
    return Rte_Write(FZC_SIG_LIDAR_DISTANCE_SENSOR_STATUS, (uint32_t)value);
}

/**
 * @brief  Write Lidar_Distance_SignalStrength (uint16_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Lidar_Distance_SignalStrength(uint16_t value)
{
    return Rte_Write(FZC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH, (uint32_t)value);
}

#endif /* RTE_SWC_LIDAR_H */
