/**
 * @file    bsw_rtetaskbodies_harness.c
 * @brief   Native test harness for the arxmlgen-generated Rte_TaskBodies_Cvc.c
 * @date    2026-08-20
 *
 * @details Links the GENERATED RTE task bodies
 *          (firmware/ecu/cvc/cfg/Rte_TaskBodies_Cvc.c — "GENERATED BY
 *          arxmlgen v1.0.0 -- DO NOT EDIT") and drives each OSEK task body
 *          through a phase script read from stdin. Each phase is one line of
 *          whitespace-separated key=value tokens:
 *
 *            op=run task=1ms
 *            op=run task=10ms
 *            op=run task=50ms
 *            op=run task=100ms
 *            op=run task=5000ms
 *            op=run task=idle idleIters=3
 *
 *          All external symbols the task bodies call are mocked in-harness
 *          with a shared call log: Os_TaskMap_RunMappedFunctions (task-map
 *          bridge), the SWC/BSW runnables, WdgM_CheckpointReached,
 *          TerminateTask and Cvc_Os_StartScheduleTables. The 1ms/10ms/50ms
 *          task bodies are verified to dispatch runnables in the exact
 *          S-OS-11 legacy order and emit WdgM checkpoints once per unique
 *          seId. The Idle task (never-terminating loop) is driven with
 *          setjmp/longjmp: the Os_TaskMap mock longjmps out after
 *          `idleIters` loop iterations so the loop body is covered without
 *          hanging. Output is a single JSON object on stdout carrying a
 *          per-op `results[]` array plus a final `state` snapshot.
 *
 *          No BSW module logic is linked — only the generated task bodies and
 *          their mocks are exercised, so production code is untouched.
 *
 * @copyright Taktflow Systems 2026
 */
#include <setjmp.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "Os_Cfg_Cvc.h"
#include "Os_TaskMap.h"
#include "WdgM.h"
#include "harness_common.h"

/* ==================================================================
 * Mock call log
 * ================================================================== */

#define CALL_LOG_MAX    48u
#define CALL_NAME_MAX   40u

static char call_log[CALL_LOG_MAX][CALL_NAME_MAX];
static uint8_t call_count;

static void log_call(const char* name)
{
    if (call_count < CALL_LOG_MAX) {
        (void)snprintf(call_log[call_count], CALL_NAME_MAX, "%s", name);
        call_count++;
    }
}

/* ---- WdgM checkpoint / TerminateTask / start-schedule counters ---- */

static uint8_t cp_list[16];
static uint8_t cp_count;
static uint8_t terminate_count;
static uint8_t start_sched_count;

/* ---- Idle-task bounded run via setjmp/longjmp ---- */

static jmp_buf idle_jmp;
static uint8_t idle_map_calls;
static uint8_t idle_limit;

/* ==================================================================
 * Mock external symbols (called by the generated task bodies)
 * ================================================================== */

void Os_TaskMap_RunMappedFunctions(TaskType TaskID)
{
    char name[CALL_NAME_MAX];
    (void)snprintf(name, CALL_NAME_MAX, "map:%u", (unsigned)TaskID);
    log_call(name);

    if (TaskID == OS_TASK_CVC_IDLE) {
        idle_map_calls++;
        if (idle_limit > 0u && idle_map_calls >= idle_limit) {
            longjmp(idle_jmp, 1);
        }
    }
}

void Can_MainFunction_Read(void)   { log_call("Can_MainFunction_Read"); }
void Can_MainFunction_Write(void)  { log_call("Can_MainFunction_Write"); }
void Can_MainFunction_BusOff(void) { log_call("Can_MainFunction_BusOff"); }
void Com_MainFunction_Rx(void)     { log_call("Com_MainFunction_Rx"); }
void Com_MainFunction_Tx(void)     { log_call("Com_MainFunction_Tx"); }
void Swc_EStop_MainFunction(void)        { log_call("Swc_EStop_MainFunction"); }
void Swc_Pedal_MainFunction(void)        { log_call("Swc_Pedal_MainFunction"); }
void Swc_VehicleState_MainFunction(void) { log_call("Swc_VehicleState_MainFunction"); }
void Swc_Dashboard_MainFunction(void)    { log_call("Swc_Dashboard_MainFunction"); }
void Swc_Heartbeat_MainFunction(void)    { log_call("Swc_Heartbeat_MainFunction"); }

Std_ReturnType WdgM_CheckpointReached(WdgM_SupervisedEntityIdType SEId)
{
    char name[CALL_NAME_MAX];
    (void)snprintf(name, CALL_NAME_MAX, "cp:%u", (unsigned)SEId);
    log_call(name);
    if (cp_count < 16u) {
        cp_list[cp_count] = (uint8_t)SEId;
        cp_count++;
    }
    return E_OK;
}

StatusType TerminateTask(void)
{
    log_call("TerminateTask");
    terminate_count++;
    return E_OK;
}

StatusType Cvc_Os_StartScheduleTables(void)
{
    log_call("StartScheduleTables");
    start_sched_count++;
    return E_OK;
}

/* ==================================================================
 * Phase model
 * ================================================================== */

enum {
    OP_RUN = 1
};

typedef struct {
    uint8_t  op;
    uint8_t  task;       /* 0=1ms 1=10ms 2=50ms 3=100ms 4=5000ms 5=idle */
    uint32_t idleIters;
} Phase;

static int parse_task(const char* s)
{
    if (strcmp(s, "1ms") == 0)    return 0;
    if (strcmp(s, "10ms") == 0)   return 1;
    if (strcmp(s, "50ms") == 0)   return 2;
    if (strcmp(s, "100ms") == 0)  return 3;
    if (strcmp(s, "5000ms") == 0) return 4;
    if (strcmp(s, "idle") == 0)   return 5;
    return -1;
}

static void reset_phase(void* phase)
{
    Phase* p = (Phase*)phase;
    p->op = OP_RUN;
    p->task = 0u;
    p->idleIters = 3u;
}

static int set_phase_field(void* phase, const char* key, const char* value)
{
    Phase* p = (Phase*)phase;

    if (strcmp(key, "op") == 0) {
        if (strcmp(value, "run") == 0) {
            p->op = OP_RUN;
        } else {
            return 1;
        }
    } else if (strcmp(key, "task") == 0) {
        int t = parse_task(value);
        if (t < 0) {
            return 1;
        }
        p->task = (uint8_t)t;
    } else if (strcmp(key, "idleIters") == 0) {
        p->idleIters = harness_parse_uint(value);
    }
    return 0;
}

static int finish_phase(void* phase, size_t index)
{
    Phase* p = (Phase*)phase;
    if (p->op == 0u) {
        fprintf(stderr, "missing/unknown op in phase %zu\n", index);
        return 1;
    }
    return 0;
}

/* ==================================================================
 * Task execution
 * ================================================================== */

static void run_task(uint8_t task)
{
    switch (task) {
    case 0: Os_Task_Cvc_1ms();    break;
    case 1: Os_Task_Cvc_10ms();   break;
    case 2: Os_Task_Cvc_50ms();   break;
    case 3: Os_Task_Cvc_100ms();  break;
    case 4: Os_Task_Cvc_5000ms(); break;
    case 5:
        idle_map_calls = 0u;
        if (setjmp(idle_jmp) == 0) {
            Os_Task_Cvc_Idle();  /* never returns normally — longjmps back */
        }
        break;
    default:
        break;
    }
}

/* ==================================================================
 * State snapshot formatting
 * ================================================================== */

static void format_task_state(char* buf, size_t bufsize, uint8_t task)
{
    size_t off = 0u;
    uint8_t i;

    static const char* task_names[6] = {
        "1ms", "10ms", "50ms", "100ms", "5000ms", "idle"
    };

    off += (size_t)snprintf(
        buf + off, bufsize - off,
        "\"state\":{"
        "\"task\":\"%s\","
        "\"callSeq\":[",
        task_names[task]);

    for (i = 0u; i < call_count; i++) {
        off += (size_t)snprintf(buf + off, bufsize - off, "%s\"%s\"",
                                (i > 0u) ? "," : "", call_log[i]);
    }

    off += (size_t)snprintf(buf + off, bufsize - off,
                            "],\"checkpoints\":[");
    for (i = 0u; i < cp_count; i++) {
        off += (size_t)snprintf(buf + off, bufsize - off, "%s%u",
                                (i > 0u) ? "," : "", (unsigned)cp_list[i]);
    }

    off += (size_t)snprintf(buf + off, bufsize - off,
                            "],\"terminateCount\":%u,"
                            "\"startSchedCount\":%u,"
                            "\"idleMapCalls\":%u}",
                            (unsigned)terminate_count,
                            (unsigned)start_sched_count,
                            (unsigned)idle_map_calls);
}

/* ==================================================================
 * main
 * ================================================================== */

int main(void)
{
    Phase phases[HARNESS_MAX_PHASES];
    size_t phase_count;
    size_t pi;
    char results_buf[HARNESS_MAX_PHASES * 2048u];
    size_t rb = 0u;

    {
        int n = harness_read_phases(phases, sizeof(phases[0]), reset_phase,
                                    set_phase_field, finish_phase);
        if (n < 0) {
            return 2;
        }
        phase_count = (size_t)n;
    }

    results_buf[0] = '\0';

    for (pi = 0u; pi < phase_count; pi++) {
        const Phase* p = &phases[pi];
        char state_buf[2048u];
        int n;

        /* Reset per-op mock state */
        call_count = 0u;
        cp_count = 0u;
        terminate_count = 0u;
        start_sched_count = 0u;
        idle_map_calls = 0u;
        idle_limit = (uint8_t)p->idleIters;

        run_task(p->task);
        format_task_state(state_buf, sizeof(state_buf), p->task);

        n = snprintf(results_buf + rb, sizeof(results_buf) - rb,
                     "%s{\"op\":\"run\",%s}",
                     (rb > 0u) ? "," : "", state_buf);
        if (n < 0 || (size_t)n >= sizeof(results_buf) - rb) {
            fprintf(stderr, "results buffer overflow\n");
            return 2;
        }
        rb += (size_t)n;
    }

    printf("{\"results\":[%s],\"state\":{\"phaseCount\":%zu}}\n",
           results_buf, phase_count);

    return 0;
}
