/**
 * @file    bsw_comcfg_harness.c
 * @brief   Native test harness for the arxmlgen-generated Com_Cfg_<Ecu>.c
 * @date    2026-08-20
 *
 * @details Links the GENERATED BSW Com configuration for one ECU
 *          (firmware/ecu/<ecu>/cfg/Com_Cfg_<Ecu>.c — "GENERATED BY arxmlgen
 *          v1.0.0 -- DO NOT EDIT") and reads the exported
 *          `const Com_ConfigType <ecu>_com_config` data tables back through a
 *          phase script read from stdin. Each phase is one line of
 *          whitespace-separated key=value tokens:
 *
 *            op=dump
 *            op=txpdu id=<pduId>
 *            op=rxpdu id=<pduId>
 *            op=sig table=tx|rx id=<signalId>
 *            op=invariants
 *
 *          Output is a single JSON object on stdout carrying a per-op
 *          `results[]` array plus a final `state` snapshot:
 *            {"results":[{"op":"txpdu","id":3,"state":{...}}],"state":{...}}
 *
 *          The ECU config symbol is selected at compile time via
 *          -DECU_TAG=<ecu> and -DECU_COM_CONFIG=<ecu>_com_config, so this one
 *          source builds one harness per ECU (e.g. bsw_comcfg_cvc_harness,
 *          bsw_comcfg_fzc_harness, ...). No BSW module logic is linked — the
 *          tables are `static const` data, so the harness only exercises the
 *          generated configuration data (DBC fidelity) without modifying any
 *          production code.
 *
 * @copyright Taktflow Systems 2026
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "Com.h"
#include "harness_common.h"

#ifndef ECU_TAG
#error "ECU_TAG must be defined at compile time (e.g. -DECU_TAG=cvc)"
#endif
#ifndef ECU_COM_CONFIG
#error "ECU_COM_CONFIG must be defined (e.g. -DECU_COM_CONFIG=cvc_com_config)"
#endif

/* Macro-expanded reference to the generated config symbol */
extern const Com_ConfigType ECU_COM_CONFIG;

/* ECU_TAG → string literal for JSON output ("cvc" etc.) */
#define ECU_TAG_STR_(x) #x
#define ECU_TAG_STR(x)  ECU_TAG_STR_(x)

/* ==================================================================
 * Mode / type name helpers (readable JSON)
 * ================================================================== */

static const char* com_mode_name(Com_TxModeType m)
{
    switch (m) {
    case COM_TX_MODE_PERIODIC: return "PERIODIC";
    case COM_TX_MODE_DIRECT:   return "DIRECT";
    case COM_TX_MODE_MIXED:    return "MIXED";
    case COM_TX_MODE_NONE:     return "NONE";
    default:                   return "?";
    }
}

static const char* com_type_name(Com_SignalType t)
{
    switch (t) {
    case COM_UINT8:  return "UINT8";
    case COM_UINT16: return "UINT16";
    case COM_SINT16: return "SINT16";
    case COM_BOOL:   return "BOOL";
    case COM_UINT32: return "UINT32";
    default:         return "?";
    }
}

/* ==================================================================
 * Table lookups
 * ================================================================== */

static const Com_TxPduConfigType* find_tx_pdu(const Com_ConfigType* cfg,
                                              PduIdType id)
{
    uint8_t i;
    for (i = 0u; i < cfg->txPduCount; i++) {
        if (cfg->txPduConfig[i].PduId == id) {
            return &cfg->txPduConfig[i];
        }
    }
    return NULL;
}

static const Com_RxPduConfigType* find_rx_pdu(const Com_ConfigType* cfg,
                                              PduIdType id)
{
    uint8_t i;
    for (i = 0u; i < cfg->rxPduCount; i++) {
        if (cfg->rxPduConfig[i].PduId == id) {
            return &cfg->rxPduConfig[i];
        }
    }
    return NULL;
}

static const Com_SignalConfigType* find_signal(const Com_ConfigType* cfg,
                                               int table, Com_SignalIdType id)
{
    const Com_SignalConfigType* tab;
    uint16_t count;
    uint16_t i;

    if (table == 1) {  /* rx */
        tab = cfg->rxSignalConfig;
        count = cfg->rxSignalCount;
    } else {           /* tx (default) */
        tab = cfg->txSignalConfig;
        count = cfg->txSignalCount;
    }

    for (i = 0u; i < count; i++) {
        if (tab[i].SignalId == id) {
            return &tab[i];
        }
    }
    return NULL;
}

/* ==================================================================
 * Structural invariants over the generated tables
 * ================================================================== */

static int invariant_tx_ids_unique(const Com_ConfigType* cfg)
{
    uint8_t i, j;
    for (i = 0u; i < cfg->txPduCount; i++) {
        for (j = i + 1u; j < cfg->txPduCount; j++) {
            if (cfg->txPduConfig[i].PduId == cfg->txPduConfig[j].PduId) {
                return 0;
            }
        }
    }
    return 1;
}

static int invariant_rx_ids_unique(const Com_ConfigType* cfg)
{
    uint8_t i, j;
    for (i = 0u; i < cfg->rxPduCount; i++) {
        for (j = i + 1u; j < cfg->rxPduCount; j++) {
            if (cfg->rxPduConfig[i].PduId == cfg->rxPduConfig[j].PduId) {
                return 0;
            }
        }
    }
    return 1;
}

static int invariant_signals_fit_in_dlc(const Com_ConfigType* cfg)
{
    uint16_t i;

    for (i = 0u; i < cfg->txSignalCount; i++) {
        const Com_SignalConfigType* s = &cfg->txSignalConfig[i];
        const Com_TxPduConfigType* p = find_tx_pdu(cfg, s->PduId);
        if (p == NULL) {
            return 0;  /* signal references an unknown TX PDU */
        }
        if ((uint16_t)s->BitPosition + (uint16_t)s->BitSize >
            (uint16_t)p->Dlc * 8u) {
            return 0;
        }
    }

    for (i = 0u; i < cfg->rxSignalCount; i++) {
        const Com_SignalConfigType* s = &cfg->rxSignalConfig[i];
        const Com_RxPduConfigType* p = find_rx_pdu(cfg, s->PduId);
        if (p == NULL) {
            return 0;
        }
        if ((uint16_t)s->BitPosition + (uint16_t)s->BitSize >
            (uint16_t)p->Dlc * 8u) {
            return 0;
        }
    }

    return 1;
}

/* Check that every E2E-protected PDU carries the standard header signals:
 * dataId @ bit 0 (size 4), alive counter @ bit 4 (size 4), CRC @ bit 8 (size 8). */
static int invariant_e2e_layout(const Com_ConfigType* cfg)
{
    uint8_t i;
    uint16_t k;

    for (i = 0u; i < cfg->txPduCount; i++) {
        const Com_TxPduConfigType* p = &cfg->txPduConfig[i];
        if (p->E2eProtected == FALSE) {
            continue;
        }
        {
            int has_dataid = 0, has_alive = 0, has_crc = 0;
            for (k = 0u; k < cfg->txSignalCount; k++) {
                const Com_SignalConfigType* s = &cfg->txSignalConfig[k];
                if (s->PduId != p->PduId) {
                    continue;
                }
                if ((s->BitPosition == 0u) && (s->BitSize == 4u)) {
                    has_dataid = 1;
                } else if ((s->BitPosition == 4u) && (s->BitSize == 4u)) {
                    has_alive = 1;
                } else if ((s->BitPosition == 8u) && (s->BitSize == 8u)) {
                    has_crc = 1;
                }
            }
            if ((has_dataid == 0) || (has_alive == 0) || (has_crc == 0)) {
                return 0;
            }
        }
    }

    for (i = 0u; i < cfg->rxPduCount; i++) {
        const Com_RxPduConfigType* p = &cfg->rxPduConfig[i];
        if (p->E2eProtected == FALSE) {
            continue;
        }
        {
            int has_dataid = 0, has_alive = 0, has_crc = 0;
            for (k = 0u; k < cfg->rxSignalCount; k++) {
                const Com_SignalConfigType* s = &cfg->rxSignalConfig[k];
                if (s->PduId != p->PduId) {
                    continue;
                }
                if ((s->BitPosition == 0u) && (s->BitSize == 4u)) {
                    has_dataid = 1;
                } else if ((s->BitPosition == 4u) && (s->BitSize == 4u)) {
                    has_alive = 1;
                } else if ((s->BitPosition == 8u) && (s->BitSize == 8u)) {
                    has_crc = 1;
                }
            }
            if ((has_dataid == 0) || (has_alive == 0) || (has_crc == 0)) {
                return 0;
            }
        }
    }

    return 1;
}

static int invariant_shadow_buffers_non_null(const Com_ConfigType* cfg)
{
    uint16_t i;
    for (i = 0u; i < cfg->txSignalCount; i++) {
        if (cfg->txSignalConfig[i].ShadowBuffer == NULL) {
            return 0;
        }
    }
    for (i = 0u; i < cfg->rxSignalCount; i++) {
        if (cfg->rxSignalConfig[i].ShadowBuffer == NULL) {
            return 0;
        }
    }
    return 1;
}

/* ==================================================================
 * Phase model
 * ================================================================== */

enum {
    OP_DUMP = 1,
    OP_TXPDU,
    OP_RXPDU,
    OP_SIG,
    OP_INVARIANTS
};

typedef struct {
    uint8_t  op;
    uint32_t id;       /* PDU or signal id */
    uint32_t table;    /* sig: 0=tx, 1=rx */
} Phase;

static int parse_op(const char* s)
{
    if (strcmp(s, "dump") == 0)        return OP_DUMP;
    if (strcmp(s, "txpdu") == 0)       return OP_TXPDU;
    if (strcmp(s, "rxpdu") == 0)       return OP_RXPDU;
    if (strcmp(s, "sig") == 0)         return OP_SIG;
    if (strcmp(s, "invariants") == 0)  return OP_INVARIANTS;
    return 0;
}

static void reset_phase(void* phase)
{
    Phase* p = (Phase*)phase;
    p->op = OP_DUMP;
    p->id = 0u;
    p->table = 0u;
}

static int set_phase_field(void* phase, const char* key, const char* value)
{
    Phase* p = (Phase*)phase;

    if (strcmp(key, "op") == 0)        p->op = (uint8_t)parse_op(value);
    else if (strcmp(key, "id") == 0)   p->id = harness_parse_uint(value);
    else if (strcmp(key, "table") == 0) {
        if (strcmp(value, "rx") == 0)  p->table = 1u;
        else if (strcmp(value, "tx") == 0) p->table = 0u;
        else return 1;
    }
    return 0;
}

static int finish_phase(void* phase, size_t index)
{
    Phase* p = (Phase*)phase;
    if (p->op == 0u) {
        fprintf(stderr, "missing/unknown op in phase %zu\n", index);
        return 1;
    }
    return 0;
}

/* ==================================================================
 * Phase execution → JSON
 * ================================================================== */

static void format_dump_state(char* buf, size_t bufsize)
{
    const Com_ConfigType* cfg = &ECU_COM_CONFIG;
    (void)snprintf(
        buf, bufsize,
        "\"state\":{"
        "\"ecu\":\"" ECU_TAG_STR(ECU_TAG) "\","
        "\"txPduCount\":%u,"
        "\"rxPduCount\":%u,"
        "\"txSignalCount\":%u,"
        "\"rxSignalCount\":%u,"
        "\"legacySignalCount\":%u,"
        "\"mainPeriodMs\":%u}",
        (unsigned)cfg->txPduCount,
        (unsigned)cfg->rxPduCount,
        (unsigned)cfg->txSignalCount,
        (unsigned)cfg->rxSignalCount,
        (unsigned)cfg->signalCount,
        (unsigned)cfg->mainFunctionPeriodMs);
}

static void format_txpdu_state(char* buf, size_t bufsize, PduIdType id)
{
    const Com_ConfigType* cfg = &ECU_COM_CONFIG;
    const Com_TxPduConfigType* p = find_tx_pdu(cfg, id);
    if (p == NULL) {
        (void)snprintf(buf, bufsize, "\"state\":{\"found\":false}");
        return;
    }
    (void)snprintf(
        buf, bufsize,
        "\"state\":{"
        "\"found\":true,"
        "\"dlc\":%u,"
        "\"cycleMs\":%u,"
        "\"mode\":\"%s\","
        "\"e2e\":%s,"
        "\"dataId\":%u,"
        "\"counterBit\":%u,"
        "\"crcBit\":%u}",
        (unsigned)p->Dlc,
        (unsigned)p->CycleTimeMs,
        com_mode_name(p->TxMode),
        (p->E2eProtected == TRUE) ? "true" : "false",
        (unsigned)p->E2eDataId,
        (unsigned)p->E2eCounterBit,
        (unsigned)p->E2eCrcBit);
}

static void format_rxpdu_state(char* buf, size_t bufsize, PduIdType id)
{
    const Com_ConfigType* cfg = &ECU_COM_CONFIG;
    const Com_RxPduConfigType* p = find_rx_pdu(cfg, id);
    if (p == NULL) {
        (void)snprintf(buf, bufsize, "\"state\":{\"found\":false}");
        return;
    }
    (void)snprintf(
        buf, bufsize,
        "\"state\":{"
        "\"found\":true,"
        "\"dlc\":%u,"
        "\"timeoutMs\":%u,"
        "\"e2e\":%s,"
        "\"dataId\":%u,"
        "\"maxDelta\":%u,"
        "\"demEvt\":%u,"
        "\"smValid\":%u,"
        "\"smInvalid\":%u,"
        "\"commStatusSigId\":%u}",
        (unsigned)p->Dlc,
        (unsigned)p->TimeoutMs,
        (p->E2eProtected == TRUE) ? "true" : "false",
        (unsigned)p->E2eDataId,
        (unsigned)p->E2eMaxDelta,
        (unsigned)p->E2eDemEventId,
        (unsigned)p->E2eSmWindowValid,
        (unsigned)p->E2eSmWindowInvalid,
        (unsigned)p->CommStatusRteSignalId);
}

static void format_sig_state(char* buf, size_t bufsize, int table,
                             Com_SignalIdType id)
{
    const Com_ConfigType* cfg = &ECU_COM_CONFIG;
    const Com_SignalConfigType* s = find_signal(cfg, table, id);
    if (s == NULL) {
        (void)snprintf(buf, bufsize, "\"state\":{\"found\":false}");
        return;
    }
    (void)snprintf(
        buf, bufsize,
        "\"state\":{"
        "\"found\":true,"
        "\"table\":\"%s\","
        "\"bitPos\":%u,"
        "\"bitSize\":%u,"
        "\"type\":\"%s\","
        "\"pduId\":%u,"
        "\"rteSignalId\":%u,"
        "\"updateBitPos\":%u}",
        (table == 1) ? "rx" : "tx",
        (unsigned)s->BitPosition,
        (unsigned)s->BitSize,
        com_type_name(s->Type),
        (unsigned)s->PduId,
        (unsigned)s->RteSignalId,
        (unsigned)s->UpdateBitPos);
}

static void format_invariants_state(char* buf, size_t bufsize)
{
    const Com_ConfigType* cfg = &ECU_COM_CONFIG;
    int tx_ids    = invariant_tx_ids_unique(cfg);
    int rx_ids    = invariant_rx_ids_unique(cfg);
    int fit       = invariant_signals_fit_in_dlc(cfg);
    int e2e       = invariant_e2e_layout(cfg);
    int bufs_ok   = invariant_shadow_buffers_non_null(cfg);
    int all       = (tx_ids && rx_ids && fit && e2e && bufs_ok) ? 1 : 0;

    (void)snprintf(
        buf, bufsize,
        "\"state\":{"
        "\"txIdsUnique\":%s,"
        "\"rxIdsUnique\":%s,"
        "\"signalsFitInDlc\":%s,"
        "\"e2eLayoutOk\":%s,"
        "\"shadowBuffersNonNull\":%s,"
        "\"allPass\":%s}",
        tx_ids ? "true" : "false",
        rx_ids ? "true" : "false",
        fit    ? "true" : "false",
        e2e    ? "true" : "false",
        bufs_ok ? "true" : "false",
        all    ? "true" : "false");
}

/* ==================================================================
 * main
 * ================================================================== */

int main(void)
{
    Phase phases[HARNESS_MAX_PHASES];
    size_t phase_count;
    size_t pi;
    char results_buf[HARNESS_MAX_PHASES * 1024u];
    size_t rb = 0u;

    {
        int n = harness_read_phases(phases, sizeof(phases[0]), reset_phase,
                                    set_phase_field, finish_phase);
        if (n < 0) {
            return 2;
        }
        phase_count = (size_t)n;
    }

    results_buf[0] = '\0';

    for (pi = 0u; pi < phase_count; pi++) {
        const Phase* p = &phases[pi];
        char state_buf[1024u];
        int n;

        switch (p->op) {
            case OP_DUMP:
                format_dump_state(state_buf, sizeof(state_buf));
                n = snprintf(results_buf + rb, sizeof(results_buf) - rb,
                             "%s{\"op\":\"dump\",%s}",
                             (rb > 0u) ? "," : "", state_buf);
                break;

            case OP_TXPDU:
                format_txpdu_state(state_buf, sizeof(state_buf), (PduIdType)p->id);
                n = snprintf(results_buf + rb, sizeof(results_buf) - rb,
                             "%s{\"op\":\"txpdu\",\"id\":%u,%s}",
                             (rb > 0u) ? "," : "",
                             (unsigned)p->id, state_buf);
                break;

            case OP_RXPDU:
                format_rxpdu_state(state_buf, sizeof(state_buf), (PduIdType)p->id);
                n = snprintf(results_buf + rb, sizeof(results_buf) - rb,
                             "%s{\"op\":\"rxpdu\",\"id\":%u,%s}",
                             (rb > 0u) ? "," : "",
                             (unsigned)p->id, state_buf);
                break;

            case OP_SIG:
                format_sig_state(state_buf, sizeof(state_buf),
                                 (int)p->table, (Com_SignalIdType)p->id);
                n = snprintf(results_buf + rb, sizeof(results_buf) - rb,
                             "%s{\"op\":\"sig\",\"table\":\"%s\",\"id\":%u,%s}",
                             (rb > 0u) ? "," : "",
                             (p->table == 1u) ? "rx" : "tx",
                             (unsigned)p->id, state_buf);
                break;

            case OP_INVARIANTS:
                format_invariants_state(state_buf, sizeof(state_buf));
                n = snprintf(results_buf + rb, sizeof(results_buf) - rb,
                             "%s{\"op\":\"invariants\",%s}",
                             (rb > 0u) ? "," : "", state_buf);
                break;

            default:
                fprintf(stderr, "unhandled op\n");
                return 2;
        }

        if (n < 0 || (size_t)n >= sizeof(results_buf) - rb) {
            fprintf(stderr, "results buffer overflow\n");
            return 2;
        }
        rb += (size_t)n;
    }

    printf("{\"results\":[%s],\"state\":{\"phaseCount\":%zu}}\n",
           results_buf, phase_count);

    return 0;
}
