/**
 * @file    Rte_Swc_DtcDisplay.h
 * @brief   Typed RTE wrappers for Swc_DtcDisplay (ICU)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_DTCDISPLAY_H
#define RTE_SWC_DTCDISPLAY_H

#include "Rte.h"
#include "Icu_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_DtcDisplay
 *
 * Usage: #include "Rte_Swc_DtcDisplay.h" in Swc_DtcDisplay source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read Brake_Status_BrakeFaultStatus (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Brake_Status_BrakeFaultStatus(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read CVC_Heartbeat_FaultStatus (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_CVC_Heartbeat_FaultStatus(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_CVC_HEARTBEAT_FAULT_STATUS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read DTC_Broadcast_ECU_Source (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_DTC_Broadcast_ECU_Source(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_DTC_BROADCAST_ECU_SOURCE, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read DTC_Broadcast_FreezeFrame0 (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_DTC_Broadcast_FreezeFrame0(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_DTC_BROADCAST_FREEZE_FRAME_0, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read DTC_Broadcast_FreezeFrame1 (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_DTC_Broadcast_FreezeFrame1(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_DTC_BROADCAST_FREEZE_FRAME_1, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read DTC_Broadcast_Number (uint16_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_DTC_Broadcast_Number(uint16_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_DTC_BROADCAST_NUMBER, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint16_t)tmp;
    }
    return status;
}

/**
 * @brief  Read DTC_Broadcast_OccurrenceCount (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_DTC_Broadcast_OccurrenceCount(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_DTC_BROADCAST_OCCURRENCE_COUNT, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read DTC_Broadcast_Status (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_DTC_Broadcast_Status(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_DTC_BROADCAST_STATUS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read FZC_Heartbeat_FaultStatus (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_FZC_Heartbeat_FaultStatus(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_FZC_HEARTBEAT_FAULT_STATUS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read Motor_Status_MotorFaultStatus (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Motor_Status_MotorFaultStatus(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read RZC_Heartbeat_FaultStatus (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_RZC_Heartbeat_FaultStatus(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_RZC_HEARTBEAT_FAULT_STATUS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read SC_Status_FaultFlags (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SC_Status_FaultFlags(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_SC_STATUS_FAULT_FLAGS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read SC_Status_FaultReason (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SC_Status_FaultReason(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_SC_STATUS_FAULT_REASON, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read Steering_Status_SteerFaultStatus (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Steering_Status_SteerFaultStatus(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_STEERING_STATUS_STEER_FAULT_STATUS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read Vehicle_State_FaultMask (uint16_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Vehicle_State_FaultMask(uint16_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_VEHICLE_STATE_FAULT_MASK, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint16_t)tmp;
    }
    return status;
}

#endif /* RTE_SWC_DTCDISPLAY_H */
