/**
 * @file    Rte_TaskBodies_Icu.c
 * @brief   Generated OSEK task bodies for ICU — legacy-order runnable dispatch (S-OS-11)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Os_Cfg_Icu.h"
#include "Os_TaskMap.h"

/* ==================================================================
 * S-OS-11 task bodies — legacy-order runnable dispatch
 *
 * Each period-group task body calls its runnables in EXACTLY the order
 * the legacy dispatcher (Rte_DispatchRunnables, Rte.c:40-105) executed
 * them: priority descending, ties broken by runnable-table index. The
 * generator proves this order equivalence over an LCM-of-periods window
 * before emitting this file and refuses the ECU otherwise.
 *
 * WdgM checkpoints replicate Rte.c:93-100 (once per unique seId per
 * dispatch, seId < RTE_MAX_RUNNABLES): the once-per-seId bookkeeping is
 * resolved at generation time — the checkpoint call is emitted after
 * the FIRST runnable of each unique valid seId in the group.
 *
 * Os_TaskMap_RunMappedFunctions() bridges the super-loop BSW slot
 * MainFunctions into the same period task (empty no-op map until the
 * ECU main registers its table via Os_TaskMap_SetTable before StartOS).
 *
 * Basic-task pattern: every period task terminates via TerminateTask()
 * (schedule-table expiry points re-activate it each period).
 * ================================================================== */

/* Forward declarations for SWC/BSW runnables */
extern void Swc_Dashboard_50ms(void);
extern void Swc_DtcDisplay_50ms(void);

/**
 * @brief   1 ms period-group task (0 runnables)
 * @note    Activated by schedule table OS_TABLE_ICU_1MS at every
 *          counter tick with tick % 1 == 0.
 */
void Os_Task_Icu_1ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_ICU_1MS);

    (void)TerminateTask();
}

/**
 * @brief   10 ms period-group task (0 runnables)
 * @note    Activated by schedule table OS_TABLE_ICU_10MS at every
 *          counter tick with tick % 10 == 0.
 */
void Os_Task_Icu_10ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_ICU_10MS);

    (void)TerminateTask();
}

/**
 * @brief   50 ms period-group task (2 runnables)
 * @note    Activated by schedule table OS_TABLE_ICU_50MS at every
 *          counter tick with tick % 50 == 0.
 */
void Os_Task_Icu_50ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_ICU_50MS);

    Swc_Dashboard_50ms();
    Swc_DtcDisplay_50ms();
    (void)TerminateTask();
}

/**
 * @brief   Idle task — lowest priority, autostarted, never terminates
 * @note    Assumption of Use (kernel os_cfg_validate_idle_task): the
 *          idle body must not return. As the autostarted task it is the
 *          scheduler-cutover bootstrap context: it starts the period
 *          schedule tables once (task call level, SC3 service
 *          protection), then loops on the idle task-map hook so the
 *          per-ECU map can bind the platform low-power idle action
 *          (e.g. Main_Hw_Wfi). With the weak-empty map the loop is the
 *          previous bare spin.
 */
void Os_Task_Icu_Idle(void)
{
    (void)Icu_Os_StartScheduleTables();

    for (;;) {
        Os_TaskMap_RunMappedFunctions(OS_TASK_ICU_IDLE);
    }
}
