/**
 * @file    Rte_Swc_Pedal.h
 * @brief   Typed RTE wrappers for Swc_Pedal (CVC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_PEDAL_H
#define RTE_SWC_PEDAL_H

#include "Rte.h"
#include "Cvc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Pedal
 *
 * Usage: #include "Rte_Swc_Pedal.h" in Swc_Pedal source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Write Torque_Request_PedalFault (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Torque_Request_PedalFault(boolean value)
{
    return Rte_Write(CVC_SIG_TORQUE_REQUEST_PEDAL_FAULT, (uint32_t)value);
}

/**
 * @brief  Write Torque_Request_PedalPosition1 (uint16_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Torque_Request_PedalPosition1(uint16_t value)
{
    return Rte_Write(CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1, (uint32_t)value);
}

/**
 * @brief  Write Torque_Request_PedalPosition2 (uint16_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Torque_Request_PedalPosition2(uint16_t value)
{
    return Rte_Write(CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2, (uint32_t)value);
}

#endif /* RTE_SWC_PEDAL_H */
