/**
 * @file    Rte_Swc_VehicleState.h
 * @brief   Typed RTE wrappers for Swc_VehicleState (CVC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_VEHICLESTATE_H
#define RTE_SWC_VEHICLESTATE_H

#include "Rte.h"
#include "Cvc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_VehicleState
 *
 * Usage: #include "Rte_Swc_VehicleState.h" in Swc_VehicleState source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Write Brake_Command_VehicleState (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Brake_Command_VehicleState(uint8_t value)
{
    return Rte_Write(CVC_SIG_BRAKE_COMMAND_VEHICLE_STATE, (uint32_t)value);
}

/**
 * @brief  Write Steer_Command_VehicleState (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Steer_Command_VehicleState(uint8_t value)
{
    return Rte_Write(CVC_SIG_STEER_COMMAND_VEHICLE_STATE, (uint32_t)value);
}

/**
 * @brief  Write Vehicle_State_E2E_AliveCounter (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Vehicle_State_E2E_AliveCounter(uint8_t value)
{
    return Rte_Write(CVC_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER, (uint32_t)value);
}

/**
 * @brief  Write Vehicle_State_E2E_CRC8 (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Vehicle_State_E2E_CRC8(uint8_t value)
{
    return Rte_Write(CVC_SIG_VEHICLE_STATE_E_2_E_CRC_8, (uint32_t)value);
}

/**
 * @brief  Write Vehicle_State_E2E_DataID (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Vehicle_State_E2E_DataID(uint8_t value)
{
    return Rte_Write(CVC_SIG_VEHICLE_STATE_E_2_E_DATA_ID, (uint32_t)value);
}

/**
 * @brief  Write Vehicle_State_FaultMask (uint16_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Vehicle_State_FaultMask(uint16_t value)
{
    return Rte_Write(CVC_SIG_VEHICLE_STATE_FAULT_MASK, (uint32_t)value);
}

/**
 * @brief  Write Vehicle_State_Mode (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Vehicle_State_Mode(uint8_t value)
{
    return Rte_Write(CVC_SIG_VEHICLE_STATE_MODE, (uint32_t)value);
}

/**
 * @brief  Write Vehicle_State_SpeedLimit (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Vehicle_State_SpeedLimit(uint8_t value)
{
    return Rte_Write(CVC_SIG_VEHICLE_STATE_SPEED_LIMIT, (uint32_t)value);
}

/**
 * @brief  Write Vehicle_State_TorqueLimit (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Vehicle_State_TorqueLimit(uint8_t value)
{
    return Rte_Write(CVC_SIG_VEHICLE_STATE_TORQUE_LIMIT, (uint32_t)value);
}

#endif /* RTE_SWC_VEHICLESTATE_H */
