/**
 * @file    Rte_Swc_EStop.h
 * @brief   Typed RTE wrappers for Swc_EStop (CVC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_ESTOP_H
#define RTE_SWC_ESTOP_H

#include "Rte.h"
#include "Cvc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_EStop
 *
 * Usage: #include "Rte_Swc_EStop.h" in Swc_EStop source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Write EStop_Broadcast_Active (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_EStop_Broadcast_Active(uint8_t value)
{
    return Rte_Write(CVC_SIG_ESTOP_BROADCAST_ACTIVE, (uint32_t)value);
}

/**
 * @brief  Write EStop_Broadcast_E2E_AliveCounter (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_EStop_Broadcast_E2E_AliveCounter(uint8_t value)
{
    return Rte_Write(CVC_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER, (uint32_t)value);
}

/**
 * @brief  Write EStop_Broadcast_E2E_CRC8 (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_EStop_Broadcast_E2E_CRC8(uint8_t value)
{
    return Rte_Write(CVC_SIG_ESTOP_BROADCAST_E_2_E_CRC_8, (uint32_t)value);
}

/**
 * @brief  Write EStop_Broadcast_E2E_DataID (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_EStop_Broadcast_E2E_DataID(uint8_t value)
{
    return Rte_Write(CVC_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID, (uint32_t)value);
}

/**
 * @brief  Write EStop_Broadcast_Source (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_EStop_Broadcast_Source(uint8_t value)
{
    return Rte_Write(CVC_SIG_ESTOP_BROADCAST_SOURCE, (uint32_t)value);
}

#endif /* RTE_SWC_ESTOP_H */
