/**
 * @file    Os_Cfg_Tcu.c
 * @brief   OSEK kernel configuration for TCU — task/schedule-table/stack tables (S-OS-11)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Os_Cfg_Tcu.h"

/* ==================================================================
 * S-OS-11 design notes
 *
 * Expiry-point offset rule: each period group gets ONE repeating
 * schedule table with Duration == period and a single expiry point at
 * offset == period, started at absolute tick 0. The group task is
 * therefore activated exactly at the counter ticks where the legacy
 * dispatcher (Rte_DispatchRunnables) fired the group's runnables
 * (tick % period == 0). Offsets are deliberately NOT staggered across
 * groups: staggering would shift activation phase and break the
 * S-OS-11 order-equivalence proof. Same-tick pileup is resolved by
 * task priority (shorter period = higher priority = runs first); the
 * generator refuses any ECU where that resolution would change the
 * legacy execution order.
 *
 * WdgM note: this file carries only kernel tables. The task BODIES —
 * including runnable dispatch order and WdgM_CheckpointReached calls
 * replicated from Rte_DispatchRunnables — are generated separately in
 * Rte_TaskBodies_Tcu.c.
 * ================================================================== */

/* ==================================================================
 * Task table — one basic task per period group + idle
 * Idle-task convention (kernel os_cfg_validate_idle_task, FMEA
 * OS-C-03): priority OS_MAX_PRIORITIES-1, autostarted in
 * OSDEFAULTAPPMODE, FULL. Its body never terminates (Assumption of Use).
 * ================================================================== */

static const Os_TaskConfigType tcu_os_task_cfg[OS_TASK_COUNT_TCU] = {
    /* Name, Entry, Priority, ActivationLimit, AutostartMask, Extended, Schedule */
    { "Tcu_1ms", Os_Task_Tcu_1ms, OS_TASK_PRIO_TCU_1MS, 1u, 0u, FALSE, FULL },
    { "Tcu_10ms", Os_Task_Tcu_10ms, OS_TASK_PRIO_TCU_10MS, 1u, 0u, FALSE, FULL },
    { "Tcu_Idle", Os_Task_Tcu_Idle, (uint8)(OS_MAX_PRIORITIES - 1u), 1u, 1u, FALSE, FULL },
};

/* ==================================================================
 * Schedule tables — one repeating table per period group
 * ================================================================== */

static const Os_ExpiryPointConfigType tcu_os_ep_1ms[1] = {
    /* Offset, TaskID, EventMask */
    { 1u, OS_TASK_TCU_1MS, 0u },
};
static const Os_ExpiryPointConfigType tcu_os_ep_10ms[1] = {
    /* Offset, TaskID, EventMask */
    { 10u, OS_TASK_TCU_10MS, 0u },
};

static const Os_ScheduleTableConfigType tcu_os_sched_table_cfg[OS_SCHED_TABLE_COUNT_TCU] = {
    /* Name, Duration, Repeating, ExpiryPoints, ExpiryPointCount */
    { "Tcu_1ms", 1u, TRUE, tcu_os_ep_1ms, 1u },
    { "Tcu_10ms", 10u, TRUE, tcu_os_ep_10ms, 1u },
};

/* ==================================================================
 * Stack budgets (Os_StackMonitorConfigType) — from sidecar os: section
 * ================================================================== */

static const Os_StackMonitorConfigType tcu_os_stack_cfg[OS_TASK_COUNT_TCU] = {
    /* TaskID, BudgetBytes */
    { OS_TASK_TCU_1MS, 1024u },
    { OS_TASK_TCU_10MS, 1024u },
    { OS_TASK_TCU_IDLE, 1024u },
};

/* ==================================================================
 * Task stack storage (Os_TaskStackConfigType) — S-OS-31 launch seam.
 * StartOS builds each task's initial PSP frame at the top of these
 * arrays via the port task-binding seam and launches the first task
 * through Os_PortStartFirstTask. 8-byte aligned (AAPCS); sizes equal
 * the monitor budgets above (kernel os_cfg_apply_task_stacks requires
 * budget <= storage).
 * ================================================================== */

static uint8 tcu_os_stack_1ms[1024] __attribute__((aligned(8)));
static uint8 tcu_os_stack_10ms[1024] __attribute__((aligned(8)));
static uint8 tcu_os_stack_idle[1024] __attribute__((aligned(8)));

static const Os_TaskStackConfigType tcu_os_task_stack_cfg[OS_TASK_COUNT_TCU] = {
    /* TaskID, StackBase, SizeBytes */
    { OS_TASK_TCU_1MS, tcu_os_stack_1ms, 1024u },
    { OS_TASK_TCU_10MS, tcu_os_stack_10ms, 1024u },
    { OS_TASK_TCU_IDLE, tcu_os_stack_idle, 1024u },
};

/* ==================================================================
 * Aggregate kernel configuration
 * ================================================================== */

const Os_ConfigType tcu_os_config = {
    .Tasks = tcu_os_task_cfg,
    .TaskCount = OS_TASK_COUNT_TCU,
    .Resources = NULL_PTR,
    .ResourceCount = 0u,
    .Alarms = NULL_PTR,
    .AlarmCount = 0u,
    .ScheduleTables = tcu_os_sched_table_cfg,
    .ScheduleTableCount = OS_SCHED_TABLE_COUNT_TCU,
    .Applications = NULL_PTR,
    .ApplicationCount = 0u,
    .TrustedFunctions = NULL_PTR,
    .TrustedFunctionCount = 0u,
    .Iocs = NULL_PTR,
    .IocCount = 0u,
    .Stacks = tcu_os_stack_cfg,
    .StackCount = OS_TASK_COUNT_TCU,
    .MemoryRegions = NULL_PTR,
    .MemoryRegionCount = 0u,
    .MemProtTasks = NULL_PTR,
    .MemProtTaskCount = 0u,
    .TaskStacks = tcu_os_task_stack_cfg,
    .TaskStackCount = OS_TASK_COUNT_TCU,
};

/**
 * @brief   Start all period-group schedule tables at absolute tick 0
 * @return  E_OK, or the last non-OK status from StartScheduleTableAbs
 * @note    Task context only (SC3 service protection). The kernel
 *          processes expiry points from the NEXT counter tick, so an
 *          absolute start of 0 fires each table first at tick == period
 *          — the legacy dispatcher's phase.
 */
StatusType Tcu_Os_StartScheduleTables(void)
{
    StatusType status = E_OK;
    uint8 idx;

    for (idx = 0u; idx < OS_SCHED_TABLE_COUNT_TCU; idx++) {
        StatusType table_status = StartScheduleTableAbs((ScheduleTableType)idx, 0u);
        if (table_status != E_OK) {
            status = table_status;
        }
    }

    return status;
}
