/**
 * @file    Rte_TaskBodies_Rzc.c
 * @brief   Generated OSEK task bodies for RZC — legacy-order runnable dispatch (S-OS-11)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Os_Cfg_Rzc.h"
#include "Os_TaskMap.h"
#include "WdgM.h"

/* ==================================================================
 * S-OS-11 task bodies — legacy-order runnable dispatch
 *
 * Each period-group task body calls its runnables in EXACTLY the order
 * the legacy dispatcher (Rte_DispatchRunnables, Rte.c:40-105) executed
 * them: priority descending, ties broken by runnable-table index. The
 * generator proves this order equivalence over an LCM-of-periods window
 * before emitting this file and refuses the ECU otherwise.
 *
 * WdgM checkpoints replicate Rte.c:93-100 (once per unique seId per
 * dispatch, seId < RTE_MAX_RUNNABLES): the once-per-seId bookkeeping is
 * resolved at generation time — the checkpoint call is emitted after
 * the FIRST runnable of each unique valid seId in the group.
 *
 * Os_TaskMap_RunMappedFunctions() bridges the super-loop BSW slot
 * MainFunctions into the same period task (weak-empty map until the
 * scheduler-cutover step provides the per-ECU table).
 *
 * Basic-task pattern: every period task terminates via TerminateTask()
 * (schedule-table expiry points re-activate it each period).
 * ================================================================== */

/* Forward declarations for SWC/BSW runnables */
extern void Swc_CurrentMonitor_MainFunction(void);
extern void Can_MainFunction_Read(void);
extern void Swc_Encoder_MainFunction(void);
extern void Swc_Motor_MainFunction(void);
extern void Com_MainFunction_Rx(void);
extern void Swc_RzcSensorFeeder_MainFunction(void);
extern void Com_MainFunction_Tx(void);
extern void Can_MainFunction_BusOff(void);
extern void Swc_Heartbeat_MainFunction(void);
extern void Swc_Battery_MainFunction(void);
extern void Swc_TempMonitor_MainFunction(void);
extern void Swc_RzcSafety_MainFunction(void);

/**
 * @brief   1 ms period-group task (2 runnables)
 * @note    Activated by schedule table OS_TABLE_RZC_1MS at every
 *          counter tick with tick % 1 == 0.
 */
void Os_Task_Rzc_1ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_RZC_1MS);

    Swc_CurrentMonitor_MainFunction();
    (void)WdgM_CheckpointReached(0x00u);
    Can_MainFunction_Read();
    (void)TerminateTask();
}

/**
 * @brief   10 ms period-group task (6 runnables)
 * @note    Activated by schedule table OS_TABLE_RZC_10MS at every
 *          counter tick with tick % 10 == 0.
 */
void Os_Task_Rzc_10ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_RZC_10MS);

    Swc_Encoder_MainFunction();
    (void)WdgM_CheckpointReached(0x02u);
    Swc_Motor_MainFunction();
    (void)WdgM_CheckpointReached(0x01u);
    Com_MainFunction_Rx();
    Swc_RzcSensorFeeder_MainFunction();
    Com_MainFunction_Tx();
    Can_MainFunction_BusOff();
    (void)TerminateTask();
}

/**
 * @brief   50 ms period-group task (1 runnable)
 * @note    Activated by schedule table OS_TABLE_RZC_50MS at every
 *          counter tick with tick % 50 == 0.
 */
void Os_Task_Rzc_50ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_RZC_50MS);

    Swc_Heartbeat_MainFunction();
    (void)WdgM_CheckpointReached(0x05u);
    (void)TerminateTask();
}

/**
 * @brief   100 ms period-group task (3 runnables)
 * @note    Activated by schedule table OS_TABLE_RZC_100MS at every
 *          counter tick with tick % 100 == 0.
 */
void Os_Task_Rzc_100ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_RZC_100MS);

    Swc_Battery_MainFunction();
    (void)WdgM_CheckpointReached(0x04u);
    Swc_TempMonitor_MainFunction();
    (void)WdgM_CheckpointReached(0x03u);
    Swc_RzcSafety_MainFunction();
    (void)WdgM_CheckpointReached(0x06u);
    (void)TerminateTask();
}

/**
 * @brief   5000 ms period-group task (0 runnables)
 * @note    Activated by schedule table OS_TABLE_RZC_5000MS at every
 *          counter tick with tick % 5000 == 0.
 */
void Os_Task_Rzc_5000ms(void)
{
    Os_TaskMap_RunMappedFunctions(OS_TASK_RZC_5000MS);

    (void)TerminateTask();
}

/**
 * @brief   Idle task — lowest priority, autostarted, never terminates
 * @note    Assumption of Use (kernel os_cfg_validate_idle_task): the
 *          idle body must not return. Platform low-power hooks (WFI)
 *          are a scheduler-cutover concern.
 */
void Os_Task_Rzc_Idle(void)
{
    for (;;) {
    }
}
