/**
 * @file    Rte_Swc_Battery.h
 * @brief   Typed RTE wrappers for Swc_Battery (RZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_BATTERY_H
#define RTE_SWC_BATTERY_H

#include "Rte.h"
#include "Rzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Battery
 *
 * Usage: #include "Rte_Swc_Battery.h" in Swc_Battery source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read RZC_Virtual_Sensors_BattVoltage_mV (uint16_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_RZC_Virtual_Sensors_BattVoltage_mV(uint16_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(RZC_SIG_RZC_VIRTUAL_SENSORS_BATT_VOLTAGE_M_V, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint16_t)tmp;
    }
    return status;
}

/**
 * @brief  Write Battery_Status_BatteryVoltage_mV (uint16_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Battery_Status_BatteryVoltage_mV(uint16_t value)
{
    return Rte_Write(RZC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V, (uint32_t)value);
}

/**
 * @brief  Write Battery_Status_E2E_AliveCounter (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Battery_Status_E2E_AliveCounter(uint8_t value)
{
    return Rte_Write(RZC_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER, (uint32_t)value);
}

/**
 * @brief  Write Battery_Status_E2E_CRC8 (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Battery_Status_E2E_CRC8(uint8_t value)
{
    return Rte_Write(RZC_SIG_BATTERY_STATUS_E_2_E_CRC_8, (uint32_t)value);
}

/**
 * @brief  Write Battery_Status_E2E_DataID (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Battery_Status_E2E_DataID(uint8_t value)
{
    return Rte_Write(RZC_SIG_BATTERY_STATUS_E_2_E_DATA_ID, (uint32_t)value);
}

/**
 * @brief  Write Battery_Status_Level (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Battery_Status_Level(uint8_t value)
{
    return Rte_Write(RZC_SIG_BATTERY_STATUS_LEVEL, (uint32_t)value);
}

#endif /* RTE_SWC_BATTERY_H */
