# language: zh-CN
功能: CVC RTE 任务体真端到端 — 总线 cadence 与 E-Stop FTTI (bsw_rtetaskbodies_cvc)

  CVC OSEK 任务体（firmware/ecu/cvc/cfg/Rte_TaskBodies_Cvc.c，由 arxmlgen
  生成——"GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT"，S-OS-11）的
  **真端到端**测试：运行在 SIL Docker 栈（vcan0）上，通过
  /api/test/bsw/rtetaskbodies/cvc 验证任务体分派的**可观测总线后果**：

    - cadence：10ms 任务体的 Com_MainFunction_Tx 让周期帧以与 DBC
      GenMsgCycleTime 兼容的 cadence 真实上总线（Vehicle_State/Torque_Request
      10ms、CVC_Heartbeat 50ms），且 E2E 有效
    - ftti：E-Stop 经 UDP DIO 注入（与 SIL-003 同一侧信道）后，0x001
      EStop_Broadcast(Active=1) 在 FTTI 预算内到达总线，且锁存广播流的
      DLC=4 / E2E dataId=1 / alive 单调 / CRC 有效；随后重启 CVC 容器
      清除断电级 E-Stop 永锁

  被测链路（全真实）：
    [UDP DIO → IoHwAb → Swc_EStop → 任务体 → Com → PduR → CanIf → vcan0]

  覆盖映射（原 S-OS-11 mock 任务体用例 → 本文件的真端到端断言）：
    - 10ms 任务 7 个 runnable 的分派顺序 → cadence（VS/Torque 10ms）
      + ftti（EStop 广播 FTTI），顺序错误的可观测后果
    - 50ms 心跳 runnable → cadence（CVC_Heartbeat 50ms）
    - TerminateTask/Idle/任务体骨架的白盒契约 → 由生成骨架的单元/符合性测试
      覆盖；本文件只断言任务体驱动的总线行为

  背景:
    假如存在:
      """
      BswRteTaskBodiesSetup: {
        phases: []
      }
      """

  规则: 真端到端 — 总线 cadence（任务体驱动 Com TX 的可观测后果）

    cadence 每次 POST 探测指定的 DBC 消息（results[0] 恒为目标消息）。

    场景: Vehicle_State 以 10ms cadence 真实上总线（10ms 任务驱动 Com TX）
      当POST "/api/test/bsw/rtetaskbodies/cvc":
      """
      {
        "phases": [
          { "op": "cadence", "targets": ["Vehicle_State"] }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        busUp: true
        ecu: "cvc"
        cycleMs: 10
        cycleOk: true
        crcValid: true
      }
      """

    场景: Torque_Request 以 10ms cadence 真实上总线（10ms 任务驱动 Com TX）
      当POST "/api/test/bsw/rtetaskbodies/cvc":
      """
      {
        "phases": [
          { "op": "cadence", "targets": ["Torque_Request"] }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        busUp: true
        ecu: "cvc"
        cycleMs: 10
        cycleOk: true
        crcValid: true
      }
      """

    场景: CVC_Heartbeat 以 50ms cadence 真实上总线（50ms 任务驱动心跳 runnable）
      当POST "/api/test/bsw/rtetaskbodies/cvc":
      """
      {
        "phases": [
          { "op": "cadence", "targets": ["CVC_Heartbeat"] }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        busUp: true
        ecu: "cvc"
        cycleMs: 50
        cycleOk: true
        crcValid: true
      }
      """

    场景: Body_Control_Cmd 以 100ms cadence 真实上总线（100ms 周期信号路径）
      当POST "/api/test/bsw/rtetaskbodies/cvc":
      """
      {
        "phases": [
          { "op": "cadence", "targets": ["Body_Control_Cmd"] }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        busUp: true
        ecu: "cvc"
        cycleMs: 100
        cycleOk: true
      }
      """

  规则: 真端到端 — E-Stop FTTI（10ms 任务分派的时延后果）

    场景: E-Stop 注入后 200ms 内广播上总线且锁存流 E2E 有效
      当POST "/api/test/bsw/rtetaskbodies/cvc":
      """
      {
        "phases": [
          { "op": "ftti", "budgetMs": 200, "restartCvc": true }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        busUp: true
        ecu: "cvc"
        estopFrameSeen: true
        withinBudget: true
        frame: {
          dlc: 4
          dlcOk: true
          dataId: 1
          dataIdOk: true
          crcValid: true
          aliveMonotonic: true
        }
      }
      """
