# language: zh-CN
功能: CVC Com 配置一致性 (bsw_comcfg_cvc)

  CVC 的 Com 模块配置（firmware/ecu/cvc/cfg/Com_Cfg_Cvc.c，由 arxmlgen 从
  DBC 生成的 BSW 配置数据表——"GENERATED BY arxmlgen v1.0.0 -- DO NOT
  EDIT"）的端到端测试：harness 链接真实生成文件并读回导出的
  `const Com_ConfigType cvc_com_config`，逐项验证 TX/RX PDU 表、信号位定义
  与 DBC 唯一真源的一致性，并运行结构不变量检查（ID 唯一、信号不越界、
  E2E 头布局、shadow 缓冲非空）。harness 只读数据表，不链接任何 BSW 逻辑，
  生产代码零改动。

  PDU/Signal ID 取自 Cvc_Cfg.h（如 CVC_COM_TX_VEHICLE_STATE=2、
  CVC_COM_TX_TORQUE_REQUEST=3、CVC_COM_RX_FZC_HEARTBEAT=0 等），断言值为
  DBC 派生的期望值。

  背景:
    假如存在:
      """
      BswComCfgSetup: {
        phases: []
      }
      """

  规则: 总览 — 配置规模

    Com_Init 消费的 cvc_com_config 汇总计数应与生成内容一致（12 个 TX PDU、
    33 个 RX PDU、58 个 TX 信号、124 个 RX 信号、主函数周期 10ms）。

    场景: 配置规模汇总
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "dump" }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        ecu: "cvc"
        txPduCount: 12
        rxPduCount: 33
        txSignalCount: 58
        rxSignalCount: 124
        mainPeriodMs: 10
      }
      """

  规则: TX PDU — 安全关键消息（DBC 一致性）

    安全关键 TX 消息的 DLC/周期/发送模式/E2E DataId 必须与 DBC 一致
    （EStop 0x001 10ms、心跳 0x010 50ms、Vehicle_State 0x100 10ms、
    Torque_Request 0x101 10ms，均 E2E 保护）。

    场景: EStop_Broadcast (id=0) DLC=4 周期10ms E2E DataId=1
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 0 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        dlc: 4
        cycleMs: 10
        mode: "PERIODIC"
        e2e: true
        dataId: 1
        counterBit: 4
        crcBit: 8
      }
      """

    场景: CVC_Heartbeat (id=1) DLC=4 周期50ms E2E DataId=2
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 1 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 4
        cycleMs: 50
        mode: "PERIODIC"
        e2e: true
        dataId: 2
      }
      """

    场景: Vehicle_State (id=2) DLC=6 周期10ms E2E DataId=5
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 2 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 6
        cycleMs: 10
        mode: "PERIODIC"
        e2e: true
        dataId: 5
      }
      """

    场景: Torque_Request (id=3) DLC=8 周期10ms E2E DataId=6
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 3 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 8
        cycleMs: 10
        mode: "PERIODIC"
        e2e: true
        dataId: 6
      }
      """

    场景: Steer_Command (id=4) DLC=8 周期10ms E2E DataId=7
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 4 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 8
        cycleMs: 10
        mode: "PERIODIC"
        e2e: true
        dataId: 7
      }
      """

  规则: TX PDU — 非安全关键与诊断（DBC 一致性）

    Body_Control_Cmd 0x350 100ms 周期无 E2E；DTC_Broadcast 0x500 与
    UDS 0x7E8 为 DIRECT 事件触发；虚拟传感器 0x600/0x601 发送关闭（NONE）。

    场景: Body_Control_Cmd (id=6) DLC=4 周期100ms 无E2E
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 6 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 4
        cycleMs: 100
        mode: "PERIODIC"
        e2e: false
      }
      """

    场景: DTC_Broadcast (id=7) DLC=8 DIRECT 触发
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 7 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 8
        cycleMs: 0
        mode: "DIRECT"
        e2e: false
      }
      """

    场景: FZC_Virtual_Sensors (id=9) 发送关闭 NONE
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 9 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        mode: "NONE"
      }
      """

  规则: RX PDU — 心跳与对等状态（DBC 一致性）

    RX 心跳的超时窗口、E2E DataId/MaxDelta、DEM 事件与 RTE 通信状态绑定
    必须与 DBC 一致（FZC 0x011 150ms、RZC 0x012 150ms）。

    场景: FZC_Heartbeat (id=0) 150ms超时 E2E DataId=3 MaxDelta=7 Dem=3
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "rxpdu", "id": 0 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        dlc: 4
        timeoutMs: 150
        e2e: true
        dataId: 3
        maxDelta: 7
        demEvt: 3
        smValid: 3
        smInvalid: 3
        commStatusSigId: 77
      }
      """

    场景: RZC_Heartbeat (id=1) 150ms超时 E2E DataId=4 MaxDelta=7 Dem=4
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "rxpdu", "id": 1 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 4
        timeoutMs: 150
        e2e: true
        dataId: 4
        maxDelta: 7
        demEvt: 4
        commStatusSigId: 134
      }
      """

    场景: Steering_Status (id=6) 150ms超时 E2E DataId=9 MaxDelta=7
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "rxpdu", "id": 6 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 8
        timeoutMs: 150
        e2e: true
        dataId: 9
        maxDelta: 7
      }
      """

  规则: RX PDU — 传感器与状态（DBC 一致性）

    Lidar 30ms 快超时（SM 失效窗口 10）；Motor 状态/电流 300ms；Battery
    3000ms 慢超时（MaxDelta 14）。

    场景: Lidar_Distance (id=10) 30ms超时 DataId=13 MaxDelta=3 SM失效窗口10
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "rxpdu", "id": 10 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 8
        timeoutMs: 30
        e2e: true
        dataId: 13
        maxDelta: 3
        smInvalid: 10
      }
      """

    场景: Motor_Status (id=11) 300ms超时 DataId=14 MaxDelta=12
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "rxpdu", "id": 11 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 8
        timeoutMs: 300
        e2e: true
        dataId: 14
        maxDelta: 12
      }
      """

    场景: Battery_Status (id=14) 3000ms超时 MaxDelta=14
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "rxpdu", "id": 14 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        dlc: 6
        timeoutMs: 3000
        e2e: true
        maxDelta: 14
      }
      """

  规则: TX 信号 — 安全关键位定义（DBC 一致性）

    Torque_Request (0x101) 与 Vehicle_State (0x100) 的关键信号位定义
    （起始位/位宽/类型）必须与 DBC 一致：Command_Pct bit16 宽8、
    Direction bit24 宽2、双踏板 14 位、踏板故障 bit54；VSM Mode bit16 宽4、
    FaultMask bit20 宽12。

    场景: Torque_Request Command_Pct (sig=21) bit16 宽8 UINT8 pdu=3
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 21 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        table: "tx"
        bitPos: 16
        bitSize: 8
        type: "UINT8"
        pduId: 3
      }
      """

    场景: Torque_Request Direction (sig=22) bit24 宽2
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 22 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        bitPos: 24
        bitSize: 2
        pduId: 3
      }
      """

    场景: Torque_Request PedalPosition1 (sig=23) bit26 宽14 UINT16
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 23 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        bitPos: 26
        bitSize: 14
        type: "UINT16"
        pduId: 3
      }
      """

    场景: Torque_Request PedalPosition2 (sig=24) bit40 宽14
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 24 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        bitPos: 40
        bitSize: 14
        pduId: 3
      }
      """

    场景: Torque_Request PedalFault (sig=25) bit54 宽1
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 25 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        bitPos: 54
        bitSize: 1
        pduId: 3
      }
      """

    场景: Vehicle_State Mode (sig=14) bit16 宽4 pdu=2
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 14 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        bitPos: 16
        bitSize: 4
        pduId: 2
      }
      """

    场景: Vehicle_State FaultMask (sig=15) bit20 宽12 UINT16
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 15 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        bitPos: 20
        bitSize: 12
        type: "UINT16"
        pduId: 2
      }
      """

    场景: E2E 头信号不绑定 RTE (sig=0 DataId) rteSignalId=65535
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 0 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        bitPos: 0
        bitSize: 4
        pduId: 0
        rteSignalId: 65535
      }
      """

  规则: RX 信号 — 关键位定义（DBC 一致性）

    FZC_Heartbeat ECU_ID bit16 宽8；SC_Status AliveCounter bit0 宽8。

    场景: FZC_Heartbeat ECU_ID (sig=3 rx) bit16 宽8 pdu=0
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "rx", "id": 3 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        table: "rx"
        bitPos: 16
        bitSize: 8
        pduId: 0
      }
      """

    场景: SC_Status AliveCounter (sig=12 rx) bit0 宽8 pdu=2
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "rx", "id": 12 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        bitPos: 0
        bitSize: 8
        pduId: 2
      }
      """

  规则: 结构不变量

    harness 对整张生成表运行结构性检查：TX/RX PDU ID 唯一、所有信号位宽
    不超过所属 PDU DLC、所有 E2E 保护 PDU 携带标准头（dataId@0 宽4 /
    alive@4 宽4 / CRC@8 宽8）、所有 shadow 缓冲非空。

    场景: 全部结构不变量通过
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "invariants" }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        txIdsUnique: true
        rxIdsUnique: true
        signalsFitInDlc: true
        e2eLayoutOk: true
        shadowBuffersNonNull: true
        allPass: true
      }
      """

  规则: 类型与边界覆盖

    覆盖 UINT32 类型信号（XCP 数据 64 位）以及查找不到时的 fail-closed
    输出（found=false，harness 对越界 PDU/信号 ID 返回不命中而非崩溃）。

    场景: XCP_RESP_CVC 数据 (sig=49 tx) 64位 UINT32 pdu=8
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "tx", "id": 49 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: true
        table: "tx"
        bitPos: 0
        bitSize: 64
        type: "UINT32"
        pduId: 8
      }
      """

    场景: 越界 TX PDU 查找返回 found=false
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "txpdu", "id": 99 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: false
      }
      """

    场景: 越界 RX PDU 查找返回 found=false
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "rxpdu", "id": 99 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: false
      }
      """

    场景: 越界 RX 信号查找返回 found=false
      当POST "/api/test/bsw/comcfg/cvc":
      """
      {
        "phases": [
          { "op": "sig", "table": "rx", "id": 999 }
        ]
      }
      """
      那么response should be:
      """
      body.json.results[0].state: {
        found: false
      }
      """
