/**
 * @file    Rte_Swc_DoorLock.h
 * @brief   Typed RTE wrappers for Swc_DoorLock (BCM)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_DOORLOCK_H
#define RTE_SWC_DOORLOCK_H

#include "Rte.h"
#include "Bcm_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_DoorLock
 *
 * Usage: #include "Rte_Swc_DoorLock.h" in Swc_DoorLock source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read Body_Control_Cmd_DoorLockCmd (boolean)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Body_Control_Cmd_DoorLockCmd(boolean *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(BCM_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (boolean)tmp;
    }
    return status;
}

/**
 * @brief  Write Door_Lock_Status_CentralLock (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Door_Lock_Status_CentralLock(boolean value)
{
    return Rte_Write(BCM_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK, (uint32_t)value);
}

/**
 * @brief  Write Door_Lock_Status_FrontLeftLock (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Door_Lock_Status_FrontLeftLock(boolean value)
{
    return Rte_Write(BCM_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK, (uint32_t)value);
}

/**
 * @brief  Write Door_Lock_Status_FrontRightLock (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Door_Lock_Status_FrontRightLock(boolean value)
{
    return Rte_Write(BCM_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK, (uint32_t)value);
}

/**
 * @brief  Write Door_Lock_Status_RearLeftLock (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Door_Lock_Status_RearLeftLock(boolean value)
{
    return Rte_Write(BCM_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK, (uint32_t)value);
}

/**
 * @brief  Write Door_Lock_Status_RearRightLock (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Door_Lock_Status_RearRightLock(boolean value)
{
    return Rte_Write(BCM_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK, (uint32_t)value);
}

#endif /* RTE_SWC_DOORLOCK_H */
