/**
 * @file    Rte_Swc_Indicators.h
 * @brief   Typed RTE wrappers for Swc_Indicators (BCM)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_INDICATORS_H
#define RTE_SWC_INDICATORS_H

#include "Rte.h"
#include "Bcm_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Indicators
 *
 * Usage: #include "Rte_Swc_Indicators.h" in Swc_Indicators source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read Body_Control_Cmd_TurnSignalCmd (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Body_Control_Cmd_TurnSignalCmd(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(BCM_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Write Indicator_State_BlinkPhaseHigh (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Indicator_State_BlinkPhaseHigh(boolean value)
{
    return Rte_Write(BCM_SIG_INDICATOR_STATE_BLINK_PHASE_HIGH, (uint32_t)value);
}

/**
 * @brief  Write Indicator_State_HazardActive (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Indicator_State_HazardActive(boolean value)
{
    return Rte_Write(BCM_SIG_INDICATOR_STATE_HAZARD_ACTIVE, (uint32_t)value);
}

/**
 * @brief  Write Indicator_State_LeftOn (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Indicator_State_LeftOn(boolean value)
{
    return Rte_Write(BCM_SIG_INDICATOR_STATE_LEFT_ON, (uint32_t)value);
}

/**
 * @brief  Write Indicator_State_RightOn (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Indicator_State_RightOn(boolean value)
{
    return Rte_Write(BCM_SIG_INDICATOR_STATE_RIGHT_ON, (uint32_t)value);
}

#endif /* RTE_SWC_INDICATORS_H */
