/**
 * @file    Rte_Swc_Lights.h
 * @brief   Typed RTE wrappers for Swc_Lights (BCM)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_LIGHTS_H
#define RTE_SWC_LIGHTS_H

#include "Rte.h"
#include "Bcm_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Lights
 *
 * Usage: #include "Rte_Swc_Lights.h" in Swc_Lights source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read Body_Control_Cmd_HeadlightCmd (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Body_Control_Cmd_HeadlightCmd(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(BCM_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Read Body_Control_Cmd_TailLightOn (boolean)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Body_Control_Cmd_TailLightOn(boolean *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(BCM_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_ON, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (boolean)tmp;
    }
    return status;
}

/**
 * @brief  Write Light_Status_BrakeLightOn (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Light_Status_BrakeLightOn(boolean value)
{
    return Rte_Write(BCM_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON, (uint32_t)value);
}

/**
 * @brief  Write Light_Status_FogLightOn (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Light_Status_FogLightOn(boolean value)
{
    return Rte_Write(BCM_SIG_LIGHT_STATUS_FOG_LIGHT_ON, (uint32_t)value);
}

/**
 * @brief  Write Light_Status_HeadlightLevel (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Light_Status_HeadlightLevel(uint8_t value)
{
    return Rte_Write(BCM_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL, (uint32_t)value);
}

/**
 * @brief  Write Light_Status_HeadlightOn (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Light_Status_HeadlightOn(boolean value)
{
    return Rte_Write(BCM_SIG_LIGHT_STATUS_HEADLIGHT_ON, (uint32_t)value);
}

/**
 * @brief  Write Light_Status_TailLightOn (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Light_Status_TailLightOn(boolean value)
{
    return Rte_Write(BCM_SIG_LIGHT_STATUS_TAIL_LIGHT_ON, (uint32_t)value);
}

#endif /* RTE_SWC_LIGHTS_H */
